import SwiftUI

// MARK: – API
let kAPIURL          = "https://test2.kurzmathis4.workers.dev"
let kDiscordURL      = "https://discord.gg/cEsMRdxsVq"
let kHelixClientID   = "1e68ku2ehgzy5cy0di3xvfy82sxpf6"
let kGQLClientID     = "kimne78kx3ncx6brgo4mv6wki5h1ko"
let kRedirectURI     = "https://mxfia19.github.io/TwitchUnblock/auth.html"
let kDeepLinkScheme  = "twitchunblock://"

/// Workers de secours, sur un autre compte Cloudflare : le principal est
/// limité à 100 000 requêtes par jour (« error code: 1027 » au-delà, jusqu'à
/// minuit UTC). Seules les routes sans base D1 y passent — VODs et lives — ;
/// sauvegarde, comptage et annonces restent sur le principal (README du site,
/// « Fallback Worker »).
let kAPIFallbackURLs: [String] = ["https://test2-fallback.vxcraftmanpetit.workers.dev"]

/// Miroirs Luminous (source « sans pub »), essayés dans l'ordre : si l'un est
/// indisponible on passe au suivant. as = Asie (historique),
/// eu/eu2/eu3 = Europe (recommandés pour le mobile).
let kLuminousHosts = [
    "as.luminous.dev",
    "eu.luminous.dev",
    "eu2.luminous.dev",
    "eu3.luminous.dev"
]

/// Proxys sans pub au format TTV.LOL v1, essayés après Luminous. Celui-ci est
/// en Albanie, où Twitch ne diffuse pas de pub ; ses variantes se lisent de
/// n'importe quelle adresse et annoncent leurs segments d'avance.
let kTTVLOLHosts = ["twitch-al.nadeko.net"]

/// Récupération de VODs supprimées : distributions CloudFront où Twitch range
/// les VODs (les plus fréquentes d'abord), plus des hôtes historiques. Le
/// dossier d'une VOD vaut SHA1("login_streamID_epoch")[:20]_login_streamID_epoch
/// — on le reconstruit puis on cherche sa playlist. Observé en octobre 2026 ;
/// voir VodRecoveryService.
let kVodRecoveryHosts = [
    "d3vd9lfkzbru3h.cloudfront.net", "d2nvs31859zcd8.cloudfront.net",
    "d3stzm2eumvgb4.cloudfront.net", "d1m7jfoe9zdc1j.cloudfront.net",
    "d2vi6trrdongqn.cloudfront.net", "d3fi1amfgojobc.cloudfront.net",
    "dgeft87wbj63p.cloudfront.net", "ddacn6pr5v0tl.cloudfront.net",
    "d2e2de1etea730.cloudfront.net", "dqrpb9wgowsf5.cloudfront.net",
    "ds0h3roq6wcgc.cloudfront.net", "d2aba1wr3818hz.cloudfront.net",
    "d3c27h4odz752x.cloudfront.net", "d1ymi26ma8va5x.cloudfront.net",
    "d1mhjrowxxagfy.cloudfront.net", "d36nr0u3xmc4mm.cloudfront.net",
    "d1oca24q5dwo6d.cloudfront.net", "d2um2qdswy1tb0.cloudfront.net",
    "vod-secure.twitch.tv", "vod-metro.twitch.tv", "vod-pop-secure.twitch.tv",
]
/// Source externe des métadonnées (id de diffusion + heure de début) des lives
/// passés : nécessaire car Twitch efface ces infos une fois la VOD supprimée.
/// Seul le nom public de la chaîne lui est transmis (voir VodRecoveryService).
let kVodRecoveryMetaAPI = "https://api.vodvod.top/channels/@"

// MARK: – Colors
extension Color {
    // Couleurs du thème choisi (accent, fonds) : voir Theme.swift.
    static var tPrimary: Color { Theme.palette.primary }
    static var tDark:    Color { Theme.palette.dark }
    static var tCard:    Color { Theme.palette.card }
    static var tSurface: Color { Theme.palette.surface }
    static var tBorder:  Color { Theme.palette.border }
    /// Version claire de l'accent (violet clair avec le thème Twitch).
    static var tPurple:  Color { Theme.palette.light }
    // Couleurs fixes, quel que soit le thème.
    static let tText      = Color(hex: "efeff1")
    static let tMuted     = Color(hex: "888888")
    static let tDanger    = Color(hex: "ff4f4d")
    static let tLive      = Color(hex: "e91916")
    static let tSuccess   = Color(hex: "00ff88")
    static let tWarning   = Color(hex: "e6e619")
    static let tVLC       = Color(hex: "ff8800")
    static let tOutplayer = Color(hex: "007aff")
    static let tInfuse    = Color(hex: "fc3c44")

    init(hex: String) {
        var h = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if h.hasPrefix("#") { h = String(h.dropFirst()) }
        var rgb: UInt64 = 0
        Scanner(string: h).scanHexInt64(&rgb)
        self.init(
            red:   Double((rgb >> 16) & 0xFF) / 255,
            green: Double((rgb >> 8)  & 0xFF) / 255,
            blue:  Double(rgb         & 0xFF) / 255
        )
    }

    /// Couleur de pseudo lisible sur fond sombre : éclaircit les couleurs trop
    /// sombres/noires (sinon un pseudo noir est illisible).
    static func readableChat(hex: String) -> Color {
        var h = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if h.hasPrefix("#") { h = String(h.dropFirst()) }
        guard h.count == 6 else { return Color(hex: hex) }
        var rgb: UInt64 = 0
        Scanner(string: h).scanHexInt64(&rgb)
        var r = Double((rgb >> 16) & 0xFF) / 255
        var g = Double((rgb >> 8)  & 0xFF) / 255
        var b = Double(rgb         & 0xFF) / 255
        // Luminance perçue
        let lum = 0.299 * r + 0.587 * g + 0.114 * b
        let minLum = 0.45
        if lum < minLum {
            // Mélange vers le blanc pour remonter au seuil minimal
            let f = min(1, (minLum - lum) / minLum + 0.15)
            r += (1 - r) * f; g += (1 - g) * f; b += (1 - b) * f
        }
        return Color(red: r, green: g, blue: b)
    }
}

// MARK: – Language
enum Lang: String, CaseIterable, Identifiable {
    case fr, en, es, ru
    var id: String { rawValue }
    var flag: String {
        switch self { case .fr: "🇫🇷"; case .en: "🇬🇧"; case .es: "🇪🇸"; case .ru: "🇷🇺" }
    }
    var label: String {
        switch self { case .fr: "Français"; case .en: "English"; case .es: "Español"; case .ru: "Русский" }
    }
    /// Traduite avec l'IA, sans relecture : on le dit à côté du choix de
    /// langue, avec un lien pour signaler les erreurs.
    var machineTranslated: Bool { self == .ru }
}

// ✨ NOUVEAU : Les sources se traduisent automatiquement !
enum LiveSource: String, CaseIterable, Identifiable, Codable {
    case auto, luminous, twitch, cloudflare
    var id: String { rawValue }

    // Lit la langue actuelle choisie par l'utilisateur
    private var currentLang: Lang {
        let saved = UserDefaults.standard.string(forKey: "lang") ?? "en"
        return Lang(rawValue: saved) ?? .en
    }

    var displayName: String {
        switch self {
        case .auto:       return translate("source_auto", currentLang)
        case .luminous:   return translate("source_luminous", currentLang)
        case .twitch:     return translate("source_twitch", currentLang)
        case .cloudflare: return translate("source_cloudflare", currentLang)
        }
    }
    
    var subtitle: String {
        switch self {
        case .auto:       return translate("source_auto_sub", currentLang)
        case .luminous:   return translate("source_luminous_sub", currentLang)
        case .twitch:     return translate("source_twitch_sub", currentLang)
        case .cloudflare: return translate("source_cloudflare_sub", currentLang)
        }
    }
    
    var emoji: String {
        switch self {
        case .auto:       return "✨"
        case .luminous:   return "💡"
        case .twitch:     return "🟣"
        case .cloudflare: return "☁️"
        }
    }
}

// MARK: – Translations
private let translations: [Lang: [String: String]] = [
    .fr: [
        "title": "Regarder Twitch sans Sub",
        "tab_home": "Accueil", "tab_search": "Recherche", "tab_library": "Mes VODs",
        "tab_direct": "Lien / ID", "settings": "Paramètres",
        "tab_history": "VODs",
        "ph_streamer": "Streamer (ex: squeezie)", "ph_keyword": "Mot-clé (ex: horreur)",
        "ph_id": "ID ou Lien de la VOD",
        "btn_unlock": "Déverrouiller", "btn_search": "Chercher",
        "btn_watch_live": "Regarder le direct", "btn_copy": "Copier",
        "btn_pip": "PiP", "btn_refresh": "🔄 Actualiser",
        "btn_logout": "Déconnexion", "btn_login_twitch": "🟣 Se connecter avec Twitch",
        "btn_clear": "Effacer",
        "loading": "Chargement...", "loading_vod": "Lancement VOD...",
        "loading_channels": "Chargement de vos chaînes...", "loading_top": "Chargement du Top...",
        "vod_ready": "VOD en lecture !", "live_on": "EN DIRECT", "offline": "HORS LIGNE",
        "offline_since": "Hors ligne depuis : ", "no_vod": "Aucune VOD trouvée.",
        "no_live": "Aucune chaîne en live pour le moment.", "vods_found": "VODs trouvées.",
        "not_found": "❌ Streamer introuvable.", "err_missing": "Nom manquant.",
        "err_network": "Erreur réseau.", "err_live": "Erreur Live.",
        "err_conn": "Erreur connexion.", "err_loading": "Erreur lors du chargement.",
        "login_prompt": "Connectez-vous pour retrouver vos chaînes préférées.",
        "login_required": "Connectez-vous pour voir les streams en cours.",
        "session_expired": "Session expirée. Veuillez vous reconnecter.",
        "lbl_vod_history": "VODs récemment regardées", "lbl_channel_history": "Streamers récents",
        "followed_channels": "Vos chaînes suivies", "top_streams": "Top streams",
        "top_fr": "France", "top_world": "Monde", "top_lang": "Top des lives", "top_lang_sub": "Langue des streamers. Par défaut celle de ton appareil ({l}).", "lang_auto": "Appareil", "copied": "Lien copié !",
        "day": "j", "hour": "h", "min": "min", "offline_msg": "Pas de stream en cours.",
        "open_vlc": "Ouvrir dans VLC", "open_outplayer": "Ouvrir dans Outplayer",
        "open_infuse": "Ouvrir dans Infuse", "proxy": "Proxy",
        "reduce": "Réduire", "back": "Retour", "live_badge": "EN DIRECT",
        "no_result": "Aucun résultat", "confirm_logout": "Êtes-vous sûr de vouloir vous déconnecter ?",
        "cancel": "Annuler", "clear_logs": "Effacer les logs", "confirm": "Confirmer ?",
        "erase": "Effacer", "export": "📤 Exporter", "logs_empty": "Aucun log",
        "logs_hint": "Lance une VOD ou un stream pour voir les logs",
        "about": "À propos", "version": "Version 1.0.0",
        "about_desc": "Regardez vos VODs et vos directs Twitch sans abonnement, avec accès à toutes les qualités. Rien à configurer.",
        "show_logs": "Afficher les logs système",
        "connected": "Connecté", "not_connected": "Non connecté",
        "history": "Historique", "vods": "VODs", "channels": "Chaînes",
        "proxy_sub": "Désactiver pour économiser le serveur (utile pour VLC)",
        "proxy_enable": "Activer le proxy", "twitch_account": "Compte Twitch",
        "language": "Langue",
        "settings_source": "Serveur / Source Vidéo",
        
        // Traductions sources
        "source_auto": "Auto",
        "source_auto_sub": "Meilleure source disponible",
        "source_luminous": "Luminous",
        "source_luminous_sub": "Sans publicité (recommandé)",
        "source_twitch": "Twitch Officiel",
        "source_twitch_sub": "Avec publicités",
        "source_cloudflare": "Cloudflare Worker",
        "source_cloudflare_sub": "Proxy personnel",

        // Chat & Points
        "chat_connected": "Chat connecté", "chat_connecting": "Connexion...",
        "chat_send_ph": "Envoyer un message…", "chat_connecting_ph": "Connexion en cours…",
        "chat_follow": "Suivre", "chat_first_message": "Premier message",
        "poll_results": "Résultats", "poll_multi": "Plusieurs choix possibles", "poll_votes": "votes", "pred_result": "Résultat", "pred_tap_to_bet": "Touche une issue pour parier", "pred_bet_on": "Miser sur « {o} »", "pred_bet": "Parier", "pred_balance": "Solde", "pred_all": "Max", "pred_my_bet": "Ton pari : {n} pts sur « {o} »", "pred_need_login": "Pour parier, connecte ta session Twitch avec le bouton des points de chaîne", "pred_bet_failed": "Pari non envoyé, réessaie", "pred_closed": "Paris fermés", "pred_one_outcome": "Tu as déjà parié sur une autre issue", "pred_max": "Mise maximale : 250 000 pts par prédiction", "pred_min": "Mise minimale : 10 pts",
        "hide_bots": "Masquer les bots", "hide_bots_sub": "Nightbot, StreamElements, Fossabot…", "hide_commands": "Masquer les commandes", "hide_commands_sub": "Les messages qui commencent par « ! ».", "muted_words": "Mots masqués", "muted_words_sub": "Séparés par des virgules : les messages qui les contiennent ne s’affichent pas.", "hidden_users": "{n} personne(s) masquée(s)", "clear": "Effacer", "hide_user": "Masquer dans le chat", "unhide_user": "Réafficher dans le chat",
        "clips": "Clips", "no_clips": "Aucun clip sur cette période", "highlights": "Highlights", "no_highlights": "Aucun highlight", "backup": "Sauvegarde", "backup_sub": "Exporte tes chaînes et catégories suivies et tes réglages dans un fichier, pour les importer ailleurs (app ou site).", "export_data": "Exporter", "import_data": "Importer", "export_done": "Fichier exporté", "import_done": "Import terminé : %d chaîne(s) ajoutée(s)", "import_bad": "Ce fichier n’est pas une sauvegarde TwitchUnblock", "playlists": "Playlists", "play_all": "Tout lire", "videos_count": "%d vidéo(s)", "no_playlists": "Aucune playlist", "err_clip": "Ce clip est introuvable", "period_day": "24 h", "period_week": "7 j", "period_month": "30 j", "period_all": "Tout",
        "notif_live": "Notifications de live", "notif_live_sub": "Prévient quand une chaîne suivie commence un live (vérifié en arrière-plan quand iOS le permet ; suivis Twitch et suivis sur cet appareil).", "notif_test": "Envoyer une notification de test", "notif_test_title": "TwitchUnblock", "notif_test_body": "Les notifications fonctionnent 🎉", "notif_test_sent": "Envoyée : elle arrive dans 3 s (quitte l'app pour la voir comme une vraie).", "notif_test_denied": "Notifications refusées : autorise-les dans Réglages iOS → TwitchUnblock.", "notif_last_never": "Aucune vérification en arrière-plan pour l'instant. iOS choisit le moment : laisse l'app en arrière-plan (sans la fermer) quelques heures.", "notif_last_run": "Dernière vérification en arrière-plan : {t}", "notif_last_failed": "échec (connexion ou jeton)", "notif_bg_off": "« Actualisation en arrière-plan » est coupée (ou le mode économie d'énergie est actif) : iOS ne réveillera pas l'app. Réglages iOS → Général → Actualisation en arrière-plan.", "notif_bg_refused": "iOS a refusé de programmer la vérification", "web_banner_title": "Connecte ta session web", "web_banner_msg": "Pour les points de chaîne, les coffres récupérés tout seuls et les prédictions : connecte-toi une fois sur twitch.tv dans l'app.", "web_banner_btn": "Connecter", "announcement_open": "Ouvrir", "dont_show_again": "Ne plus afficher", "notif_live_title": "{u} est en live",
        "chapters": "Chapitres", "close": "Fermer",
        "made_by": "Fait par", "source_ios": "Code source de l'app", "web_version": "Version web", "credits_thanks": "Merci à BetterTTV, FrankerFaceZ, 7TV, recent-messages et Luminous.", "not_affiliated": "Projet indépendant, non affilié à Twitch.",
        "update_title": "Mise à jour disponible", "update_msg": "La version {v} est sortie (tu as la {c}). Mets-la à jour depuis Feather, SideStore ou AltStore.", "update_whats_new": "Voici ce qui a changé depuis ta version :", "update_open": "Mettre à jour", "later": "Plus tard", "update_available": "Mise à jour disponible : {v}", "update_check": "Vérifier les mises à jour", "update_none": "L'app est à jour", "version_label": "Version", "discord_join": "Rejoindre le Discord",
        "discord_title": "Rejoins le Discord", "discord_msg": "Nouveautés, bugs, idées : la communauté TwitchUnblock est sur Discord. Tu peux aussi le retrouver plus tard dans Réglages → À propos.",
        "update_msg_short": "Une nouvelle version de TwitchUnblock est disponible. Installe-la depuis Feather, SideStore ou AltStore.",
        "see_channel": "Voir la chaîne", "highlight_words": "Mots surlignés", "highlight_words_sub": "Séparés par des virgules. Les messages qui les contiennent (ou qui te mentionnent) sont mis en avant.",
        "pinned": "Message épinglé", "pinned_by": "Épinglé par {u}", "pinned_short": "Épinglé", "just_now": "à l'instant", "minutes_ago": "il y a {n} min", "hours_ago": "il y a {n} h", "pin_left": "encore {n} min",
        "thread_title": "Fil", "thread_reply_to": "Réponse à",
        "follow": "Suivre", "following": "Suivi", "hype_level": "Niveau",
        "raid_to": "Raid vers", "join": "Rejoindre", "viewers": "spectateurs",
        "customize": "Personnalisation",
        "cfg_title": "Titre du live", "cfg_title_sub": "Afficher le titre au-dessus du chat",
        "cfg_pinned": "Messages épinglés", "cfg_pinned_sub": "Afficher le bandeau des messages épinglés",
        "cfg_follow": "Bouton suivre", "cfg_follow_sub": "Afficher le bouton Suivre / Ne plus suivre",
        "cfg_streak": "Série de visionnage", "cfg_streak_sub": "Afficher le badge 🔥 de ta série",
        "cfg_events": "Sondages & prédictions", "cfg_events_sub": "Afficher sondages, prédictions et hype train",
        "cfg_raids": "Système de raid", "cfg_raids_sub": "Bannière + rejoindre automatiquement la chaîne raidée",
        "cache_section": "Cache emotes & badges",
        "vod_chat": "Chat de la VOD",
        "rewind": "Rembobiner", "back_to_live": "Direct",
        "recover_title": "VOD non listée",
        "unlisted_vod": "VOD non listée",
        "unlisted_gone": "Plus disponible",
        "unlisted_hint": "Les VODs non listées (supprimées ou masquées) sont reconstruites depuis une source externe, tant que Twitch sert encore leurs segments.",
        "home_followed": "Suivies",
        "see_offline": "Voir les chaînes hors ligne",
        "offline_all_live": "Toutes tes chaînes suivies sont en live !",
        "changelog": "Journal des modifications",
        "changelog_sub": "Toutes les nouveautés, version par version",
        "changelog_installed": "Installée",
        "changelog_available": "Disponible",
        "changelog_failed": "Impossible de charger le journal des modifications.",
        "changelog_retry": "Réessayer",
        "ob_tour": "Visite guidée",
        "ob_back": "Précédent",
        "ob_tap_here": "Touche-le pour continuer",
        "ob_home_title": "Tes lives",
        "ob_home_text": "Tes chaînes suivies en direct, le top des lives, et tes chaînes hors ligne dans leur propre onglet. Pas de compte ? Touche « Suivre » sur la page d’une chaîne : elle arrive ici.",
        "ob_searchtab_title": "Recherche",
        "ob_searchtab_text": "Pour trouver une chaîne ou ouvrir une VOD.",
        "ob_search_title": "Une chaîne ou une VOD",
        "ob_search_text": "Tape un pseudo pour ses lives, VODs, highlights, playlists et clips — les VODs récemment supprimées ou masquées y figurent aussi, marquées « VOD non listée ». Ou colle le lien d’une VOD pour l’ouvrir directement.",
        "ob_library_title": "Mes VODs",
        "ob_library_text": "Tes VODs reprennent là où tu t’étais arrêté.",
        "ob_settings_title": "Paramètres",
        "ob_settings_text": "Ton avatar ouvre les paramètres : compte Twitch (facultatif) et session web pour les points de chaîne, lecteur, chat, sauvegarde… et le journal des modifications.",
        "ob_player_title": "Dans le lecteur",
        "ob_tip_zoom": "Écarte deux doigts sur la vidéo pour zoomer.",
        "ob_tip_seek": "Fais glisser la barre d’une VOD : l’instant visé s’affiche.",
        "ob_tip_lock": "Écran verrouillé et Dynamic Island : le live ou la VOD en cours, avec ses commandes.",
        "ob_tip_more": "Image dans l’image, minuteur de veille, et le chat avec les points de chaîne.",
        "switching_source": "Changement de source…",
        "fill_screen": "Remplir l'écran (paysage)",
        "fill_screen_sub": "Agrandit l'image jusqu'aux bords en paysage, au prix du haut et du bas. Désactivé, l'image reste entière et laisse des bandes égales sur les côtés. Sans effet en portrait.",
        "web_expired": "Session web expirée",
        "web_expired_sub": "Twitch a refusé la session web. Les points de chaîne, sondages et prédictions restent indisponibles tant qu'elle n'est pas rétablie.",
        "web_reconnect": "Rétablir la session",
        "history_vods_title": "Vos dernières VODs",
        "history_vods_empty": "Aucune VOD dans votre historique pour le moment.",
        "vod_chat_loading": "Chargement du chat…",
        "vod_chat_empty": "Aucun message à cet instant de la VOD",
        "cache_size": "Espace utilisé", "cache_files": "fichiers",
        "cache_clear": "Vider",
        "cache_auto": "Vider en quittant",
        "cache_auto_sub": "Purge le cache en quittant le live ou l'application",
        "account_api": "Connexion API", "account_api_sub": "Chat, chaînes suivies et Top",
        "account_web": "Session web (points)", "account_web_sub": "Requise pour les points de chaîne",
        "login_points_hint": "Pour les points de chaîne, connecte-toi aussi en « Session web » depuis les Réglages ⚙️",
        "points_title": "Points de chaîne",
        "points_connect_title": "Connecte ton compte Twitch",
        "points_connect_desc": "Nécessaire pour afficher ton solde et réclamer les coffres.",
        "points_connect_btn": "Se connecter",
        "points_loading": "Chargement des récompenses…",
        "points_none": "Aucune récompense disponible",
        "points_claim_bonus": "Réclamer le bonus", "points_bonus_claimed": "Bonus réclamé ! 🎉",
        "points_redeem": "Racheter", "points_insufficient": "Insuff.",
        "points_out_of_stock": "Rupture de stock", "points_paused": "En pause",
        "points_input_ph": "Votre message…", "points_unit": "pts",
        "points_redeemed": "réclamé ✓", "points_error": "Erreur",
        "points_network_error": "Erreur réseau", "points_missing": "Il te manque",
        "points_by": "par",
        "err_not_enough": "Pas assez de points", "err_reward_not_found": "Récompense introuvable",
        "err_points_disabled": "Points désactivés", "err_already_claimed": "Déjà réclamé",
        "err_cooldown": "Attends un peu",
        "err_properties_mismatch": "Récompense modifiée, réessaie",
        "err_stream_offline": "Le stream n'est pas en direct",
        "auto_claim": "Réclamer les coffres auto",
        "auto_claim_sub": "Récupère les coffres de points dès qu'ils apparaissent.",
        "player_section": "Lecteur vidéo",
        "sec_general": "Général", "sec_player": "Lecteur", "sec_chat": "Chat", "sec_other": "À propos",
        "sec_account_sub": "Connexion, session web, utilisation",
        "sec_general_sub": "Langue, coffres, minuteur, historique, cache",
        "sec_player_sub": "Lecteur immersif, faible latence, débogage",
        "sec_chat_sub": "Messages récents, apparence, taille",
        "sec_other_sub": "Version et journaux", "sec_labs_sub": "Nouveautés encore en rodage", "offline_channels": "Hors ligne", "cat_followed": "Suivies", "cat_all": "Toutes", "cat_followed_empty": "Aucune catégorie suivie", "cat_followed_empty_msg": "Suis des catégories sur Twitch, ou ouvre une catégorie et touche « Suivre ».", "cat_followed_empty_msg_local": "Ouvre une catégorie et touche « Suivre » : elle apparaîtra ici.", "ob_skip": "Passer", "ob_next": "Suivant", "ob_start": "C’est parti", "ob_replay": "Revoir le tutoriel", "ob_welcome_title": "Bienvenue sur TwitchUnblock", "ob_welcome_text": "Lives et VODs Twitch en qualité maximale, sans abonnement, avec le vrai chat. Choisis ta langue, puis fais le tour de l’app en une minute.", "bot_commands": "Commandes des bots", "bot_commands_sub": "Nightbot, StreamElements, Fossabot, Moobot : sans écrire dans le chat", "bot_commands_filter": "Filtrer les commandes", "bot_commands_none": "Aucune commande trouvée", "bot_commands_none_msg": "Cette chaîne n’utilise pas Nightbot, StreamElements, Fossabot ni Moobot, ou n’y a pas de commande publique.", "copied_cmd": "{c} copiée", "home_list": "Accueil en liste", "home_list_sub": "Chaînes en liste comme sur Twitch (miniature à gauche) au lieu de la grille", "layout_grid": "Afficher en grille", "layout_list": "Afficher en liste", "local_follow_empty": "Suis des chaînes sans compte", "local_follow_empty_msg": "Ouvre la page d’une chaîne et touche « Suivre » : elle apparaîtra ici dès qu’elle est en live.", "login_optional_msg": "Facultatif : pour tes chaînes suivies Twitch, le chat et les points. Tout le reste marche sans compte.", "on_this_device": "sur cet appareil",
        "chat_behavior": "Comportement du chat",
        "cfg_recent": "Charger les messages récents",
        "cfg_recent_sub": "Twitch n'envoie rien d'antérieur à l'arrivée. Les dernières lignes sont récupérées auprès de recent-messages.robotty.de, un service tiers.",
        "cfg_autocomplete": "Autocomplétion",
        "cfg_autocomplete_sub": "Propose emotes et pseudos pendant la frappe.",
        "cfg_deleted": "Afficher les messages supprimés",
        "cfg_deleted_sub": "Garde barrés les messages retirés par la modération au lieu de les faire disparaître.",
        "copy_message": "Copier le message", "mention_user": "Mentionner",
        "msg_copied": "Message copié",
        "chat_sizing": "Taille du chat",
        "cfg_timestamps": "Horodatage", "cfg_timestamps_sub": "Affiche l'heure devant chaque message.",
        "cfg_font_size": "Taille du texte", "cfg_msg_spacing": "Espace entre messages",
        "cfg_badge_scale": "Taille des badges", "cfg_emote_scale": "Taille des emotes",
        "cfg_chat_width": "Largeur du chat",
        "cfg_chat_width_sub": "En paysage seulement, que le chat soit en colonne ou posé sur l'image.",
        "reset_defaults": "Rétablir les valeurs par défaut",
        "vlc_player": "Lecteur VLC",
        "vlc_player_sub": "Contrôles maison : double-tap ±10s, rembobinage live. (pas de PiP)",
        "go_live": "EN DIRECT",

        // Catégories
        "streams": "Streams", "categories": "Catégories",
        "cat_search_ph": "Rechercher une catégorie…",
        "load_more": "Charger plus", "more_needs_login": "Sans compte, Twitch ne donne que les 100 premiers. Connecte-toi à Twitch pour voir la suite", "feedback": "Signaler un bug ou proposer une idée", "feedback_sub": "Un problème, une idée : ton message arrive directement au développeur.", "report_problem": "Signaler un problème", "fb_bug": "🐞 Bug", "fb_idea": "💡 Idée", "fb_other": "💬 Autre", "fb_ph_bug": "Que s’est-il passé ? Qu’attendais-tu ? Sur quelle chaîne ou quelle VOD ?", "fb_ph_idea": "Ton idée, et à quoi elle servirait.", "fb_ph_other": "Ton message.", "fb_contact_ph": "Pseudo Discord ou e-mail (facultatif)", "fb_info": "Joint automatiquement :", "fb_send": "Envoyer", "fb_thanks": "Merci ! Ton message a bien été envoyé.", "fb_failed": "Envoi impossible, réessaie plus tard.", "fb_too_many": "Trop de messages d’un coup : réessaie dans une heure.", "about_channel": "À propos de {u}", "followers": "followers", "about_empty": "Pas de description", "show_recent": "Streamers récents", "show_recent_sub": "Raccourcis vers les dernières chaînes ouvertes, dans Recherche.",
        "sort_viewers_desc": "Plus de spectateurs",
        "sort_viewers_asc": "Moins de spectateurs",
        "sort_name": "Nom (A → Z)",

        // Minuteur de veille
        "sleep_timer": "Minuteur de veille",
        "sleep_timer_sub": "Coupe la lecture au bout du délai choisi.",
        "sleep_minutes": "min", "sleep_hour": "1 h", "sleep_2hours": "2 h",
        "sleep_remaining": "Temps restant",
        "sleep_cancel": "Annuler",
        "sleep_add": "+15 min",

        // Débogage
        "vibecoded": "Projet vibecodé : l’app est écrite avec l’aide d’assistants IA, puis relue et testée à la main. Des bugs peuvent passer, signale-les sur Discord.", "debug_section": "Fonctionnalités en test",
        "debug_note": "Nouveautés encore en rodage : elles peuvent changer ou mal fonctionner. Tes retours sont les bienvenus sur Discord.",
        "dbg_latency": "Afficher la latence",
        "dbg_latency_sub": "Pastille sur le lecteur : retard du direct en secondes",
        "dbg_chat_delay": "Synchro auto du chat",
        "dbg_chat_delay_sub": "Retarde les messages de ton retard sur le direct pour les caler sur l'image",
        "sleep_custom_ph": "Durée", "sleep_start": "Démarrer",
        "sleep_set": "Régler", "sleep_edit": "Modifier",
        "low_latency": "Mode faible latence",
        "low_latency_sub": "Reste au plus près du direct (comme sur Twitch). Peut charger un peu plus souvent sur une connexion lente. S'applique au prochain direct lancé.",
        "delete_vod": "Retirer de l'historique",
        "usage_section": "Utilisation de l'app",
        "usage_returning": "Reviennent",
        "usage_loyalty_once": "1 seul jour", "usage_loyalty_few": "2 à 6 jours",
        "usage_loyalty_regular": "7 à 29 jours", "usage_loyalty_daily": "30 jours et +",
        "usage_avg_days": "moy.", "usage_since": "depuis le",
        "usage_today": "Aujourd'hui", "usage_week": "7 jours", "usage_month": "30 jours",
        "usage_versions": "Par version",
        "usage_refresh": "Actualiser",
        "usage_tap_refresh": "Appuie sur Actualiser pour relever les compteurs.",
        "usage_worker_missing": "Le serveur n'a pas encore les routes de comptage. Voir worker/README.md pour les déployer.",
        "usage_error": "Compteurs indisponibles pour le moment.",
        "usage_share": "Partager mon utilisation",
        "usage_share_sub": "Sans compte : un identifiant tiré au hasard et la version de l'app. Connecté : ton compte Twitch, pour te compter une seule fois sur l'app et le site. Une fois par heure au plus, ni chaînes regardées ni adresse IP. Couper efface tout du serveur.",
        "immersive_player": "Lecteur immersif",
        "immersive_player_sub": "Commandes et infos par-dessus l'image, qui s'effacent toutes seules. Désactivé : lecteur Apple avec ses contrôles, PiP et plein écran système.",
        "quality": "Qualité",
        "rewind_sub": "Revenir en arrière dans le direct",
        "menu_chat_only": "Chat seul",
        "chat_mode_column": "Chat : colonne",
        "chat_mode_overlay": "Chat : superposé",
        "chat_mode_hidden": "Chat : masqué",
        "menu_chat_only_sub": "Masque la vidéo et garde la conversation en plein écran.",
        "menu_reload_emotes": "Recharger emotes et badges",
        "menu_reload_emotes_sub": "Vide le cache et récupère tout à neuf.",
        "menu_reconnect": "Reconnecter le chat",
        "menu_reconnect_sub": "Relance la connexion sans quitter le direct.",
        "menu_color": "Couleur du pseudo",
        "menu_color_sub": "Change ta couleur dans le chat.",
        "menu_needs_login": "Connexion requise",
        "menu_chatters": "Chatteurs",
        "menu_chatters_sub": "Qui est présent dans le chat.",
        "menu_chatters_search": "Filtrer les pseudos…",
        "menu_chatters_empty": "Personne annoncé sur cette chaîne",
        "menu_chatters_waiting": "En attente de la liste du chat…",
        "menu_chatters_note": "Twitch a fermé son API de présence : seul le chat IRC annonce encore les arrivées, et uniquement sur les chaînes de taille modeste. La liste peut donc rester vide sur les gros directs.",
        "color_needs_relogin": "Déconnecte-toi puis reconnecte-toi : l'autorisation « changer la couleur » a été ajoutée après ta connexion.",
        "color_network": "Impossible de joindre Twitch.",
        "color_bad_request": "Couleur refusée par Twitch.",
        "color_failed": "Twitch a refusé le changement de couleur.",
        "role_broadcaster": "Streamer", "role_moderator": "Modérateurs",
        "ph_search": "Streamer, lien ou ID de VOD…",
        "btn_open": "Ouvrir",
        "hint_is_vod": "Ouvrira cette VOD",
        "hint_is_channel": "Cherchera cette chaîne",
        "err_bad_vod": "Lien ou ID de VOD invalide.",
        "search_empty_title": "Cherche une chaîne ou colle un lien",
        "search_empty_msg": "Tape un nom de streamer, ou colle le lien / l'ID d'une VOD : l'app reconnaît les deux.",
        "no_followed_live": "Aucune de vos chaînes n'est en direct",
        "no_followed_live_msg": "Jetez un œil au Top ou aux catégories en attendant.",
        "history_vods_empty_msg": "Les VODs que vous lancez apparaîtront ici, avec la reprise de lecture.",
        "chat_sync_hint": "Chat en avance ou en retard sur l'image ?",
        "chat_sync_later": "Retarder le chat (+1 s)",
        "chat_sync_earlier": "Avancer le chat (−1 s)",
        "chat_sync_reset": "Revenir à la synchro auto seule",
        "chat_sync_adjust": "Ajustement de la synchro",
        "chat_sync_adjust_sub": "Chat encore en avance sur l'image ? Ajoute quelques secondes. En retard ? Retires-en. Aussi depuis la pastille ⏱ au-dessus du chat.",
        "lang_ai_note": "Traduction faite avec l'IA, pas encore relue : si une phrase sonne faux, dis-le-nous.",
        "lang_ai_report": "Signaler une erreur de traduction",
        "lang_ai_badge": "Traduit avec l'IA",
        "switch_account": "Changer de compte",
        "switch_account_sub": "Twitch demandera tes identifiants : connecte-toi avec l'autre compte.",
        "vod_muted_here": "Son coupé par Twitch (musique protégée)",
        "vod_muted_skip": "Passer",
        "vod_unmuted": "Son d'origine rétabli sur les passages coupés",
        "restore_muted": "Rétablir le son des passages coupés",
        "restore_muted_sub": "Twitch coupe le son des passages avec de la musique protégée. Un jour ou deux après le live, l'original est encore disponible : l'app le remet quand elle peut. Sans effet sur AirPlay.",
        "appearance": "Apparence",
        "accent_color": "Couleur d'accent",
        "background_theme": "Fond",
        "accent_twitch": "Violet Twitch",
        "accent_blue": "Bleu",
        "accent_green": "Vert",
        "accent_pink": "Rose",
        "accent_orange": "Orange",
        "accent_red": "Rouge",
        "accent_teal": "Turquoise",
        "bg_dark": "Sombre",
        "bg_oled": "Noir OLED",
        "bg_slate": "Ardoise",
        "liquid_glass": "Verre liquide",
        "liquid_glass_sub": "Barre d'onglets flottante et boutons en verre, façon iOS 26.",
        "liquid_glass_unavailable": "Nécessite iOS 26 ou plus récent.",
        "fb_add_photos": "Ajouter des captures",
        "fb_mine": "Mes signalements",
        "fb_mine_empty": "Les retours envoyés depuis l'app apparaîtront ici, avec les réponses.",
        "fb_thanks_follow": "Merci ! Tu suivras la réponse dans « Mes signalements ».",
        "fb_reply_ph": "Répondre…",
        "fb_reply_send": "Envoyer",
        "fb_reply_failed": "Réponse non envoyée, réessaie.",
        "fb_team": "TwitchUnblock",
        "fb_you": "Toi",
        "fb_status_line": "État : {s}",
        "fb_gone": "Ce retour n'est plus disponible.",
        "fb_status_new": "Reçu",
        "fb_status_accepted": "Accepté",
        "fb_status_progress": "En cours",
        "fb_status_done": "Fait",
        "fb_status_refused": "Refusé",
        "adm_feedback": "Gérer les retours",
        "adm_feedback_sub": "Répondre, changer l'état, supprimer — visible seulement par ton compte",
        "adm_all": "Tous",
        "adm_await": "À répondre",
        "adm_awaiting": "Réponse de la personne",
        "adm_empty": "Aucun retour dans cet état.",
        "adm_them": "La personne",
        "adm_reply_ph": "Répondre (visible par la personne)…",
        "adm_delete": "Supprimer",
        "adm_delete_confirm": "Supprimer ce retour et ses photos ?",
        "adm_contact": "Contact",
        "adm_info": "Infos techniques",
        "adm_failed": "Action impossible, réessaie.",
        "adm_hook_ok": "Discord : dernier envoi réussi ({d})",
        "adm_hook_fail": "Discord : dernier envoi refusé ({d}) — {e}",
        "adm_hook_missing": "Discord : secret FEEDBACK_WEBHOOK absent du Worker",
        "adm_hook_never": "Discord : aucun envoi depuis la mise à jour",
        "adm_hook_test": "Tester l'envoi Discord",
        "adm_hook_test_ok": "Message de test envoyé sur Discord.",
    ],
    .en: [
        "title": "Watch Twitch No Sub",
        "tab_home": "Home", "tab_search": "Search", "tab_library": "My VODs",
        "tab_direct": "Link / ID", "settings": "Settings",
        "tab_history": "VODs",
        "ph_streamer": "Streamer (ex: shroud)", "ph_keyword": "Keyword (ex: horror)",
        "ph_id": "VOD ID or Link",
        "btn_unlock": "Unlock", "btn_search": "Search",
        "btn_watch_live": "Watch live", "btn_copy": "Copy",
        "btn_pip": "PiP", "btn_refresh": "🔄 Refresh",
        "btn_logout": "Logout", "btn_login_twitch": "🟣 Log in with Twitch",
        "btn_clear": "Clear",
        "loading": "Loading...", "loading_vod": "Loading VOD...",
        "loading_channels": "Loading your channels...", "loading_top": "Loading Top...",
        "vod_ready": "VOD Playing!", "live_on": "LIVE NOW", "offline": "OFFLINE",
        "offline_since": "Offline since: ", "no_vod": "No VODs found.",
        "no_live": "No live channels at the moment.", "vods_found": "VODs found.",
        "not_found": "❌ Streamer not found.", "err_missing": "Name missing.",
        "err_network": "Network error.", "err_live": "Live error.",
        "err_conn": "Connection error.", "err_loading": "Error loading data.",
        "login_prompt": "Log in to find your favorite channels.",
        "login_required": "Please log in to view live streams.",
        "session_expired": "Session expired. Please log in again.",
        "lbl_vod_history": "Recently watched VODs", "lbl_channel_history": "Recent Streamers",
        "followed_channels": "Followed channels", "top_streams": "Top streams",
        "top_fr": "France", "top_world": "World", "top_lang": "Top streams", "top_lang_sub": "Streamer language. Defaults to your device language ({l}).", "lang_auto": "Device", "copied": "Link copied!",
        "day": "d", "hour": "h", "min": "min", "offline_msg": "Stream is offline.",
        "open_vlc": "Open in VLC", "open_outplayer": "Open in Outplayer",
        "open_infuse": "Open in Infuse", "proxy": "Proxy",
        "reduce": "Reduce", "back": "Back", "live_badge": "LIVE",
        "no_result": "No result", "confirm_logout": "Are you sure you want to log out?",
        "cancel": "Cancel", "clear_logs": "Clear logs", "confirm": "Confirm?",
        "erase": "Clear", "export": "📤 Export", "logs_empty": "No logs",
        "logs_hint": "Launch a VOD or stream to see logs",
        "about": "About", "version": "Version 1.0.0",
        "about_desc": "Watch Twitch VODs and live streams without a subscription, at full quality. Nothing to set up.",
        "show_logs": "Show system logs",
        "connected": "Connected", "not_connected": "Not connected",
        "history": "History", "vods": "VODs", "channels": "Channels",
        "proxy_sub": "Disable to save server resources (useful for VLC)",
        "proxy_enable": "Enable proxy", "twitch_account": "Twitch Account",
        "language": "Language",
        "settings_source": "Video Server / Source",
        
        // Traductions sources
        "source_auto": "Auto",
        "source_auto_sub": "Best available source",
        "source_luminous": "Luminous",
        "source_luminous_sub": "Ad-free (recommended)",
        "source_twitch": "Official Twitch",
        "source_twitch_sub": "With ads",
        "source_cloudflare": "Cloudflare Worker",
        "source_cloudflare_sub": "Personal proxy",

        // Chat & Points
        "chat_connected": "Chat connected", "chat_connecting": "Connecting...",
        "chat_send_ph": "Send a message…", "chat_connecting_ph": "Connecting…",
        "chat_follow": "Follow", "chat_first_message": "First message",
        "poll_results": "Results", "poll_multi": "Multiple choices allowed", "poll_votes": "votes", "pred_result": "Result", "pred_tap_to_bet": "Tap an outcome to predict", "pred_bet_on": "Predict “{o}”", "pred_bet": "Predict", "pred_balance": "Balance", "pred_all": "Max", "pred_my_bet": "Your prediction: {n} pts on “{o}”", "pred_need_login": "To predict, connect your Twitch session with the channel points button", "pred_bet_failed": "Prediction not sent, try again", "pred_closed": "Predictions closed", "pred_one_outcome": "You already predicted another outcome", "pred_max": "Maximum: 250,000 pts per prediction", "pred_min": "Minimum: 10 pts",
        "hide_bots": "Hide bots", "hide_bots_sub": "Nightbot, StreamElements, Fossabot…", "hide_commands": "Hide commands", "hide_commands_sub": "Messages starting with “!”.", "muted_words": "Muted words", "muted_words_sub": "Comma-separated: messages containing them are not shown.", "hidden_users": "{n} hidden user(s)", "clear": "Clear", "hide_user": "Hide in chat", "unhide_user": "Show in chat again",
        "clips": "Clips", "no_clips": "No clips for this period", "highlights": "Highlights", "no_highlights": "No highlights", "backup": "Backup", "backup_sub": "Export your followed channels, categories and settings to a file, to import them elsewhere (app or website).", "export_data": "Export", "import_data": "Import", "export_done": "File exported", "import_done": "Import done: %d channel(s) added", "import_bad": "This file is not a TwitchUnblock backup", "playlists": "Playlists", "play_all": "Play all", "videos_count": "%d video(s)", "no_playlists": "No playlists", "err_clip": "This clip could not be found", "period_day": "24h", "period_week": "7d", "period_month": "30d", "period_all": "All",
        "notif_live": "Live notifications", "notif_live_sub": "Get notified when a followed channel goes live (checked in the background when iOS allows it; Twitch follows and follows on this device).", "notif_test": "Send a test notification", "notif_test_title": "TwitchUnblock", "notif_test_body": "Notifications are working 🎉", "notif_test_sent": "Sent: it arrives in 3 s (leave the app to see it like a real one).", "notif_test_denied": "Notifications denied: allow them in iOS Settings → TwitchUnblock.", "notif_last_never": "No background check yet. iOS picks the moment: leave the app in the background (without closing it) for a few hours.", "notif_last_run": "Last background check: {t}", "notif_last_failed": "failed (network or token)", "notif_bg_off": "“Background App Refresh” is off (or Low Power Mode is on): iOS won’t wake the app. iOS Settings → General → Background App Refresh.", "notif_bg_refused": "iOS refused to schedule the check", "web_banner_title": "Connect your web session", "web_banner_msg": "For channel points, auto-claimed chests and predictions: sign in once to twitch.tv inside the app.", "web_banner_btn": "Connect", "announcement_open": "Open", "dont_show_again": "Don’t show again", "notif_live_title": "{u} is live",
        "chapters": "Chapters", "close": "Close",
        "made_by": "Made by", "source_ios": "App source code", "web_version": "Web version", "credits_thanks": "Thanks to BetterTTV, FrankerFaceZ, 7TV, recent-messages and Luminous.", "not_affiliated": "Independent project, not affiliated with Twitch.",
        "update_title": "Update available", "update_msg": "Version {v} is out (you have {c}). Update it from Feather, SideStore or AltStore.", "update_whats_new": "Here’s what’s new since your version:", "update_open": "Update", "later": "Later", "update_available": "Update available: {v}", "update_check": "Check for updates", "update_none": "The app is up to date", "version_label": "Version", "discord_join": "Join the Discord",
        "discord_title": "Join the Discord", "discord_msg": "News, bugs, ideas: the TwitchUnblock community is on Discord. You can also find it later in Settings → About.",
        "update_msg_short": "A new version of TwitchUnblock is available. Install it from Feather, SideStore or AltStore.",
        "see_channel": "See channel", "highlight_words": "Highlighted words", "highlight_words_sub": "Comma-separated. Messages containing them (or mentioning you) stand out.",
        "pinned": "Pinned message", "pinned_by": "Pinned by {u}", "pinned_short": "Pinned", "just_now": "just now", "minutes_ago": "{n} min ago", "hours_ago": "{n} h ago", "pin_left": "{n} min left",
        "thread_title": "Thread", "thread_reply_to": "Reply to",
        "follow": "Follow", "following": "Following", "hype_level": "Level",
        "raid_to": "Raid to", "join": "Join", "viewers": "viewers",
        "customize": "Customization",
        "cfg_title": "Stream title", "cfg_title_sub": "Show the title above the chat",
        "cfg_pinned": "Pinned messages", "cfg_pinned_sub": "Show the pinned message banner",
        "cfg_follow": "Follow button", "cfg_follow_sub": "Show the Follow / Unfollow button",
        "cfg_streak": "Watch streak", "cfg_streak_sub": "Show your 🔥 streak badge",
        "cfg_events": "Polls & predictions", "cfg_events_sub": "Show polls, predictions and hype train",
        "cfg_raids": "Raid system", "cfg_raids_sub": "Banner + auto-join the raided channel",
        "cache_section": "Emote & badge cache",
        "vod_chat": "VOD chat",
        "rewind": "Rewind", "back_to_live": "Live",
        "recover_title": "Unlisted VOD",
        "unlisted_vod": "Unlisted VOD",
        "unlisted_gone": "No longer available",
        "unlisted_hint": "Unlisted VODs (deleted or hidden) are rebuilt from an external source, as long as Twitch still serves their segments.",
        "home_followed": "Following",
        "see_offline": "See offline channels",
        "offline_all_live": "All your followed channels are live!",
        "changelog": "Changelog",
        "changelog_sub": "Everything new, version by version",
        "changelog_installed": "Installed",
        "changelog_available": "Available",
        "changelog_failed": "Couldn’t load the changelog.",
        "changelog_retry": "Retry",
        "ob_tour": "Take the tour",
        "ob_back": "Back",
        "ob_tap_here": "Tap it to continue",
        "ob_home_title": "Your streams",
        "ob_home_text": "Your followed channels that are live, the top streams, and your offline channels in their own tab. No account? Tap “Follow” on a channel page and it shows up here.",
        "ob_searchtab_title": "Search",
        "ob_searchtab_text": "To find a channel or open a VOD.",
        "ob_search_title": "A channel or a VOD",
        "ob_search_text": "Type a name for their lives, VODs, highlights, playlists and clips — recently deleted or hidden VODs show up too, marked “Unlisted VOD”. Or paste a VOD link to open it right away.",
        "ob_library_title": "My VODs",
        "ob_library_text": "Your VODs resume where you left off.",
        "ob_settings_title": "Settings",
        "ob_settings_text": "Your avatar opens the settings: Twitch account (optional) and web session for channel points, player, chat, backup… and the changelog.",
        "ob_player_title": "In the player",
        "ob_tip_zoom": "Spread two fingers on the video to zoom in.",
        "ob_tip_seek": "Drag a VOD’s seek bar: the time you’re seeking to shows up.",
        "ob_tip_lock": "Lock screen and Dynamic Island: the live or VOD you’re watching, with its controls.",
        "ob_tip_more": "Picture in picture, sleep timer, and the chat with channel points.",
        "switching_source": "Switching source…",
        "fill_screen": "Fill the screen (landscape)",
        "fill_screen_sub": "Zooms the picture to the edges in landscape, at the cost of the top and bottom. Left off, the whole picture shows with even bars on the sides. No effect in portrait.",
        "web_expired": "Web session expired",
        "web_expired_sub": "Twitch rejected the web session. Channel points, polls and predictions stay unavailable until it is restored.",
        "web_reconnect": "Restore the session",
        "history_vods_title": "Your recent VODs",
        "history_vods_empty": "No VOD in your history yet.",
        "vod_chat_loading": "Loading chat…",
        "vod_chat_empty": "No messages at this point of the VOD",
        "cache_size": "Storage used", "cache_files": "files",
        "cache_clear": "Clear",
        "cache_auto": "Clear on exit",
        "cache_auto_sub": "Purge the cache when leaving the stream or the app",
        "account_api": "API login", "account_api_sub": "Chat, followed channels and Top",
        "account_web": "Web session (points)", "account_web_sub": "Required for channel points",
        "login_points_hint": "For channel points, also connect the \"Web session\" from Settings ⚙️",
        "points_title": "Channel Points",
        "points_connect_title": "Connect your Twitch account",
        "points_connect_desc": "Required to show your balance and claim chests.",
        "points_connect_btn": "Log in",
        "points_loading": "Loading rewards…",
        "points_none": "No rewards available",
        "points_claim_bonus": "Claim bonus", "points_bonus_claimed": "Bonus claimed! 🎉",
        "points_redeem": "Redeem", "points_insufficient": "Low",
        "points_out_of_stock": "Out of stock", "points_paused": "Paused",
        "points_input_ph": "Your message…", "points_unit": "pts",
        "points_redeemed": "redeemed ✓", "points_error": "Error",
        "points_network_error": "Network error", "points_missing": "You need",
        "points_by": "by",
        "err_not_enough": "Not enough points", "err_reward_not_found": "Reward not found",
        "err_points_disabled": "Points disabled", "err_already_claimed": "Already claimed",
        "err_cooldown": "Wait a moment",
        "err_properties_mismatch": "Reward changed, try again",
        "err_stream_offline": "Stream is not live",
        "auto_claim": "Auto-claim chests",
        "auto_claim_sub": "Collects point chests as soon as they appear.",
        "player_section": "Video player",
        "sec_general": "General", "sec_player": "Player", "sec_chat": "Chat", "sec_other": "About",
        "sec_account_sub": "Sign-in, web session, usage",
        "sec_general_sub": "Language, chests, sleep timer, history, cache",
        "sec_player_sub": "Immersive player, low latency, debug",
        "sec_chat_sub": "Recent messages, appearance, sizing",
        "sec_other_sub": "Version and logs", "sec_labs_sub": "New features still being polished", "offline_channels": "Offline", "cat_followed": "Followed", "cat_all": "All", "cat_followed_empty": "No followed categories", "cat_followed_empty_msg": "Follow categories on Twitch, or open a category and tap “Follow”.", "cat_followed_empty_msg_local": "Open a category and tap “Follow”: it will show up here.", "ob_skip": "Skip", "ob_next": "Next", "ob_start": "Let’s go", "ob_replay": "Replay the tutorial", "ob_welcome_title": "Welcome to TwitchUnblock", "ob_welcome_text": "Twitch lives and VODs at full quality, with no subscription, and the real chat. Pick your language, then take a one-minute tour of the app.", "bot_commands": "Bot commands", "bot_commands_sub": "Nightbot, StreamElements, Fossabot, Moobot: without typing in chat", "bot_commands_filter": "Filter commands", "bot_commands_none": "No commands found", "bot_commands_none_msg": "This channel doesn’t use Nightbot, StreamElements, Fossabot or Moobot, or has no public commands there.", "copied_cmd": "{c} copied", "home_list": "Home as a list", "home_list_sub": "Channels in a list like on Twitch (thumbnail on the left) instead of a grid", "layout_grid": "Show as grid", "layout_list": "Show as list", "local_follow_empty": "Follow channels without an account", "local_follow_empty_msg": "Open a channel page and tap “Follow”: it will show up here as soon as it goes live.", "login_optional_msg": "Optional: for your Twitch follows, chat and channel points. Everything else works without an account.", "on_this_device": "on this device",
        "chat_behavior": "Chat behaviour",
        "cfg_recent": "Load recent messages",
        "cfg_recent_sub": "Twitch sends nothing from before you join. Recent lines are fetched from recent-messages.robotty.de, a third-party service.",
        "cfg_autocomplete": "Autocomplete",
        "cfg_autocomplete_sub": "Suggests emotes and names while typing.",
        "cfg_deleted": "Show deleted messages",
        "cfg_deleted_sub": "Keeps moderated messages struck through instead of removing them.",
        "copy_message": "Copy message", "mention_user": "Mention",
        "msg_copied": "Message copied",
        "chat_sizing": "Chat sizing",
        "cfg_timestamps": "Timestamps", "cfg_timestamps_sub": "Shows the time in front of each message.",
        "cfg_font_size": "Font size", "cfg_msg_spacing": "Message spacing",
        "cfg_badge_scale": "Badge scale", "cfg_emote_scale": "Emote scale",
        "cfg_chat_width": "Chat width",
        "cfg_chat_width_sub": "Landscape only, whether the chat is a column or sits on the video.",
        "reset_defaults": "Reset to defaults",
        "vlc_player": "VLC player",
        "vlc_player_sub": "Custom controls: double-tap ±10s, live rewind. (no PiP)",
        "go_live": "LIVE",

        // Categories
        "streams": "Streams", "categories": "Categories",
        "cat_search_ph": "Search a category…",
        "load_more": "Load more", "more_needs_login": "Without an account, Twitch only gives the first 100. Log in with Twitch to see more", "feedback": "Report a bug or suggest an idea", "feedback_sub": "A problem or an idea: your message goes straight to the developer.", "report_problem": "Report a problem", "fb_bug": "🐞 Bug", "fb_idea": "💡 Idea", "fb_other": "💬 Other", "fb_ph_bug": "What happened? What did you expect? On which channel or VOD?", "fb_ph_idea": "Your idea, and what it would be useful for.", "fb_ph_other": "Your message.", "fb_contact_ph": "Discord name or email (optional)", "fb_info": "Attached automatically:", "fb_send": "Send", "fb_thanks": "Thanks! Your message was sent.", "fb_failed": "Could not send, try again later.", "fb_too_many": "Too many messages at once: try again in an hour.", "about_channel": "About {u}", "followers": "followers", "about_empty": "No description yet", "show_recent": "Recent Streamers", "show_recent_sub": "Shortcuts to the channels you opened last, in Search.",
        "sort_viewers_desc": "Most viewers",
        "sort_viewers_asc": "Fewest viewers",
        "sort_name": "Name (A → Z)",

        // Sleep timer
        "sleep_timer": "Sleep timer",
        "sleep_timer_sub": "Stops playback once the delay is over.",
        "sleep_minutes": "min", "sleep_hour": "1 h", "sleep_2hours": "2 h",
        "sleep_remaining": "Time left",
        "sleep_cancel": "Cancel",
        "sleep_add": "+15 min",

        // Debug
        "vibecoded": "Vibe-coded project: the app is written with AI coding assistants, then reviewed and tested by hand. Bugs can slip through, report them on Discord.", "debug_section": "Features in testing",
        "debug_note": "New features still being polished: they may change or misbehave. Feedback is welcome on Discord.",
        "dbg_latency": "Show latency",
        "dbg_latency_sub": "Player badge: how far behind live, in seconds",
        "dbg_chat_delay": "Auto chat sync",
        "dbg_chat_delay_sub": "Delays messages by how far behind live you are, so they match the video",
        "sleep_custom_ph": "Duration", "sleep_start": "Start",
        "sleep_set": "Set", "sleep_edit": "Edit",
        "low_latency": "Low latency mode",
        "low_latency_sub": "Stays as close to live as possible (like on Twitch). May buffer a bit more on a slow connection. Applies to the next stream you open.",
        "delete_vod": "Remove from history",
        "usage_section": "App usage",
        "usage_returning": "Came back",
        "usage_loyalty_once": "1 day only", "usage_loyalty_few": "2 to 6 days",
        "usage_loyalty_regular": "7 to 29 days", "usage_loyalty_daily": "30 days and up",
        "usage_avg_days": "avg.", "usage_since": "since",
        "usage_today": "Today", "usage_week": "7 days", "usage_month": "30 days",
        "usage_versions": "By version",
        "usage_refresh": "Refresh",
        "usage_tap_refresh": "Tap Refresh to read the counters.",
        "usage_worker_missing": "The server does not have the counting routes yet. See worker/README.md to deploy them.",
        "usage_error": "Counters unavailable right now.",
        "usage_share": "Share my usage",
        "usage_share_sub": "Logged out: a random install identifier and the app version. Logged in: your Twitch account, so you count once across the app and the website. At most once an hour, no channels watched, no IP address. Turning it off erases it all from the server.",
        "immersive_player": "Immersive player",
        "immersive_player_sub": "Controls and info over the picture, fading out on their own. Off: Apple's player with its own controls, PiP and system full screen.",
        "quality": "Quality",
        "rewind_sub": "Go back within the live stream",
        "menu_chat_only": "Chat only",
        "chat_mode_column": "Chat: column",
        "chat_mode_overlay": "Chat: overlay",
        "chat_mode_hidden": "Chat: hidden",
        "menu_chat_only_sub": "Hides the video and gives the chat the whole screen.",
        "menu_reload_emotes": "Refresh emotes and badges",
        "menu_reload_emotes_sub": "Clears the cache and fetches everything anew.",
        "menu_reconnect": "Reconnect chat",
        "menu_reconnect_sub": "Restarts the connection without leaving the stream.",
        "menu_color": "Username color",
        "menu_color_sub": "Change your colour in chat.",
        "menu_needs_login": "Login required",
        "menu_chatters": "Chatters",
        "menu_chatters_sub": "Who is in the chat right now.",
        "menu_chatters_search": "Filter names…",
        "menu_chatters_empty": "Nobody announced on this channel",
        "menu_chatters_waiting": "Waiting for the chat list…",
        "menu_chatters_note": "Twitch shut down its presence API: only IRC still announces people joining, and only on modestly sized channels. The list can therefore stay empty on big streams.",
        "color_needs_relogin": "Log out and back in: the “change colour” permission was added after you signed in.",
        "color_network": "Could not reach Twitch.",
        "color_bad_request": "Colour rejected by Twitch.",
        "color_failed": "Twitch refused the colour change.",
        "role_broadcaster": "Broadcaster", "role_moderator": "Moderators",
        "ph_search": "Streamer, link or VOD ID…",
        "btn_open": "Open",
        "hint_is_vod": "Will open this VOD",
        "hint_is_channel": "Will search this channel",
        "err_bad_vod": "Invalid VOD link or ID.",
        "search_empty_title": "Search a channel or paste a link",
        "search_empty_msg": "Type a streamer name, or paste a VOD link / ID — the app recognises both.",
        "no_followed_live": "None of your channels are live",
        "no_followed_live_msg": "Have a look at the Top or the categories meanwhile.",
        "history_vods_empty_msg": "VODs you play show up here, with resume playback.",
        "chat_sync_hint": "Chat ahead of or behind the video?",
        "chat_sync_later": "Delay chat (+1 s)",
        "chat_sync_earlier": "Show chat sooner (−1 s)",
        "chat_sync_reset": "Back to auto sync only",
        "chat_sync_adjust": "Sync adjustment",
        "chat_sync_adjust_sub": "Chat still ahead of the video? Add a few seconds. Behind? Take some off. Also from the ⏱ badge above the chat.",
        "lang_ai_note": "Translated with AI, not yet reviewed: if something sounds off, let us know.",
        "lang_ai_report": "Report a translation mistake",
        "lang_ai_badge": "Translated with AI",
        "switch_account": "Switch account",
        "switch_account_sub": "Twitch will ask for your credentials: sign in with the other account.",
        "vod_muted_here": "Sound muted by Twitch (copyrighted music)",
        "vod_muted_skip": "Skip",
        "vod_unmuted": "Original sound restored on muted parts",
        "restore_muted": "Restore muted sound",
        "restore_muted_sub": "Twitch mutes parts with copyrighted music. For a day or two after the stream the original is still available: the app puts it back when it can. No effect over AirPlay.",
        "appearance": "Appearance",
        "accent_color": "Accent color",
        "background_theme": "Background",
        "accent_twitch": "Twitch purple",
        "accent_blue": "Blue",
        "accent_green": "Green",
        "accent_pink": "Pink",
        "accent_orange": "Orange",
        "accent_red": "Red",
        "accent_teal": "Teal",
        "bg_dark": "Dark",
        "bg_oled": "OLED black",
        "bg_slate": "Slate",
        "liquid_glass": "Liquid Glass",
        "liquid_glass_sub": "Floating tab bar and glass buttons, iOS 26 style.",
        "liquid_glass_unavailable": "Requires iOS 26 or later.",
        "fb_add_photos": "Add screenshots",
        "fb_mine": "My reports",
        "fb_mine_empty": "Reports sent from the app will show up here, with the replies.",
        "fb_thanks_follow": "Thanks! Follow the reply in “My reports”.",
        "fb_reply_ph": "Reply…",
        "fb_reply_send": "Send",
        "fb_reply_failed": "Reply not sent, try again.",
        "fb_team": "TwitchUnblock",
        "fb_you": "You",
        "fb_status_line": "Status: {s}",
        "fb_gone": "This report is no longer available.",
        "fb_status_new": "Received",
        "fb_status_accepted": "Accepted",
        "fb_status_progress": "In progress",
        "fb_status_done": "Done",
        "fb_status_refused": "Declined",
        "adm_feedback": "Manage feedback",
        "adm_feedback_sub": "Reply, change the status, delete — only visible to your account",
        "adm_all": "All",
        "adm_await": "Awaiting reply",
        "adm_awaiting": "Reply from the person",
        "adm_empty": "No feedback with this status.",
        "adm_them": "The person",
        "adm_reply_ph": "Reply (the person will see it)…",
        "adm_delete": "Delete",
        "adm_delete_confirm": "Delete this report and its photos?",
        "adm_contact": "Contact",
        "adm_info": "Technical info",
        "adm_failed": "Couldn't do that, try again.",
        "adm_hook_ok": "Discord: last delivery succeeded ({d})",
        "adm_hook_fail": "Discord: last delivery refused ({d}) — {e}",
        "adm_hook_missing": "Discord: the FEEDBACK_WEBHOOK secret is missing from the Worker",
        "adm_hook_never": "Discord: nothing sent since the update",
        "adm_hook_test": "Test Discord delivery",
        "adm_hook_test_ok": "Test message sent to Discord.",
    ],
    .es: [
        "title": "Ver Twitch sin Sub",
        "tab_home": "Inicio", "tab_search": "Buscar", "tab_library": "Mis VODs",
        "tab_direct": "Enlace / ID", "settings": "Ajustes",
        "tab_history": "VODs",
        "ph_streamer": "Streamer (ej: ibai)", "ph_keyword": "Palabra (ej: horror)",
        "ph_id": "ID o Enlace VOD",
        "btn_unlock": "Desbloquear", "btn_search": "Buscar",
        "btn_watch_live": "Ver directo", "btn_copy": "Copiar",
        "btn_pip": "PiP", "btn_refresh": "🔄 Actualizar",
        "btn_logout": "Cerrar sesión", "btn_login_twitch": "🟣 Iniciar sesión con Twitch",
        "btn_clear": "Borrar",
        "loading": "Cargando...", "loading_vod": "Cargando VOD...",
        "loading_channels": "Cargando tus canales...", "loading_top": "Cargando Top...",
        "vod_ready": "VOD Reproduciendo!", "live_on": "EN VIVO", "offline": "DESCONECTADO",
        "offline_since": "Desconectado desde: ", "no_vod": "No se encontraron VODs.",
        "no_live": "No hay canales en vivo ahora.", "vods_found": "VODs encontrados.",
        "not_found": "❌ Streamer no encontrado.", "err_missing": "Falta el nombre.",
        "err_network": "Error de red.", "err_live": "Error de directo.",
        "err_conn": "Error de conexión.", "err_loading": "Error al cargar.",
        "login_prompt": "Inicia sesión para encontrar tus canales favoritos.",
        "login_required": "Inicia sesión para ver los streams.",
        "session_expired": "Sesión expirada. Inicia sesión de nuevo.",
        "lbl_vod_history": "VODs recientes", "lbl_channel_history": "Streamers recientes",
        "followed_channels": "Canales seguidos", "top_streams": "Top streams",
        "top_fr": "Francia", "top_world": "Mundo", "top_lang": "Top directos", "top_lang_sub": "Idioma de los streamers. Por defecto, el de tu dispositivo ({l}).", "lang_auto": "Dispositivo", "copied": "Enlace copiado!",
        "day": "d", "hour": "h", "min": "min", "offline_msg": "No hay directo en curso.",
        "open_vlc": "Abrir en VLC", "open_outplayer": "Abrir en Outplayer",
        "open_infuse": "Abrir en Infuse", "proxy": "Proxy",
        "reduce": "Reducir", "back": "Volver", "live_badge": "EN VIVO",
        "no_result": "Sin resultado", "confirm_logout": "¿Seguro que quieres cerrar sesión?",
        "cancel": "Cancelar", "clear_logs": "Borrar logs", "confirm": "¿Confirmar?",
        "erase": "Borrar", "export": "📤 Exportar", "logs_empty": "Sin logs",
        "logs_hint": "Lanza un VOD o stream para ver los logs",
        "about": "Acerca de", "version": "Versión 1.0.0",
        "about_desc": "Ve VODs y directos de Twitch sin suscripción, con acceso a todas las calidades. Nada que configurar.",
        "show_logs": "Mostrar logs del sistema",
        "connected": "Conectado", "not_connected": "No conectado",
        "history": "Historial", "vods": "VODs", "channels": "Canales",
        "proxy_sub": "Desactivar para ahorrar el servidor (útil para VLC)",
        "proxy_enable": "Activar proxy", "twitch_account": "Cuenta de Twitch",
        "language": "Idioma",
        "settings_source": "Servidor / Fuente de Video",
        
        // Traducciones fuentes
        "source_auto": "Auto",
        "source_auto_sub": "Mejor fuente disponible",
        "source_luminous": "Luminous",
        "source_luminous_sub": "Sin anuncios (recomendado)",
        "source_twitch": "Twitch Oficial",
        "source_twitch_sub": "Con anuncios",
        "source_cloudflare": "Cloudflare Worker",
        "source_cloudflare_sub": "Proxy personal",

        // Chat & Points
        "chat_connected": "Chat conectado", "chat_connecting": "Conectando...",
        "chat_send_ph": "Enviar un mensaje…", "chat_connecting_ph": "Conectando…",
        "chat_follow": "Seguir", "chat_first_message": "Primer mensaje",
        "poll_results": "Resultados", "poll_multi": "Varias opciones posibles", "poll_votes": "votos", "pred_result": "Resultado", "pred_tap_to_bet": "Toca un resultado para apostar", "pred_bet_on": "Apostar por «{o}»", "pred_bet": "Apostar", "pred_balance": "Saldo", "pred_all": "Máx", "pred_my_bet": "Tu apuesta: {n} pts por «{o}»", "pred_need_login": "Para apostar, conecta tu sesión de Twitch con el botón de puntos del canal", "pred_bet_failed": "Apuesta no enviada, inténtalo de nuevo", "pred_closed": "Apuestas cerradas", "pred_one_outcome": "Ya apostaste por otro resultado", "pred_max": "Máximo: 250 000 pts por predicción", "pred_min": "Mínimo: 10 pts",
        "hide_bots": "Ocultar bots", "hide_bots_sub": "Nightbot, StreamElements, Fossabot…", "hide_commands": "Ocultar comandos", "hide_commands_sub": "Los mensajes que empiezan por «!».", "muted_words": "Palabras silenciadas", "muted_words_sub": "Separadas por comas: los mensajes que las contienen no se muestran.", "hidden_users": "{n} persona(s) oculta(s)", "clear": "Borrar", "hide_user": "Ocultar en el chat", "unhide_user": "Mostrar en el chat",
        "clips": "Clips", "no_clips": "No hay clips en este periodo", "highlights": "Destacados", "no_highlights": "Sin destacados", "backup": "Copia de seguridad", "backup_sub": "Exporta tus canales y categorías seguidos y tus ajustes a un archivo, para importarlos en otro lugar (app o web).", "export_data": "Exportar", "import_data": "Importar", "export_done": "Archivo exportado", "import_done": "Importación terminada: %d canal(es) añadido(s)", "import_bad": "Este archivo no es una copia de TwitchUnblock", "playlists": "Listas", "play_all": "Reproducir todo", "videos_count": "%d vídeo(s)", "no_playlists": "Sin listas", "err_clip": "No se encontró este clip", "period_day": "24 h", "period_week": "7 d", "period_month": "30 d", "period_all": "Todo",
        "notif_live": "Notificaciones de directo", "notif_live_sub": "Avisa cuando un canal seguido empieza un directo (se comprueba en segundo plano cuando iOS lo permite; canales seguidos en Twitch y en este dispositivo).", "notif_test": "Enviar una notificación de prueba", "notif_test_title": "TwitchUnblock", "notif_test_body": "Las notificaciones funcionan 🎉", "notif_test_sent": "Enviada: llega en 3 s (sal de la app para verla como una real).", "notif_test_denied": "Notificaciones denegadas: permítelas en Ajustes de iOS → TwitchUnblock.", "notif_last_never": "Aún no hay comprobación en segundo plano. iOS elige el momento: deja la app en segundo plano (sin cerrarla) unas horas.", "notif_last_run": "Última comprobación en segundo plano: {t}", "notif_last_failed": "error (conexión o token)", "notif_bg_off": "«Actualización en segundo plano» está desactivada (o el modo de bajo consumo está activo): iOS no despertará la app. Ajustes de iOS → General → Actualización en segundo plano.", "notif_bg_refused": "iOS se negó a programar la comprobación", "web_banner_title": "Conecta tu sesión web", "web_banner_msg": "Para los puntos del canal, los cofres recogidos solos y las predicciones: inicia sesión una vez en twitch.tv dentro de la app.", "web_banner_btn": "Conectar", "announcement_open": "Abrir", "dont_show_again": "No volver a mostrar", "notif_live_title": "{u} está en directo",
        "chapters": "Capítulos", "close": "Cerrar",
        "made_by": "Hecho por", "source_ios": "Código fuente de la app", "web_version": "Versión web", "credits_thanks": "Gracias a BetterTTV, FrankerFaceZ, 7TV, recent-messages y Luminous.", "not_affiliated": "Proyecto independiente, no afiliado a Twitch.",
        "update_title": "Actualización disponible", "update_msg": "Ya salió la versión {v} (tienes la {c}). Actualízala desde Feather, SideStore o AltStore.", "update_whats_new": "Esto es lo nuevo desde tu versión:", "update_open": "Actualizar", "later": "Más tarde", "update_available": "Actualización disponible: {v}", "update_check": "Buscar actualizaciones", "update_none": "La app está al día", "version_label": "Versión", "discord_join": "Unirse al Discord",
        "discord_title": "Únete al Discord", "discord_msg": "Novedades, bugs, ideas: la comunidad de TwitchUnblock está en Discord. También lo encontrarás en Ajustes → Acerca de.",
        "update_msg_short": "Hay una nueva versión de TwitchUnblock. Instálala desde Feather, SideStore o AltStore.",
        "see_channel": "Ver canal", "highlight_words": "Palabras resaltadas", "highlight_words_sub": "Separadas por comas. Los mensajes que las contienen (o te mencionan) se destacan.",
        "pinned": "Mensaje fijado", "pinned_by": "Fijado por {u}", "pinned_short": "Fijado", "just_now": "ahora mismo", "minutes_ago": "hace {n} min", "hours_ago": "hace {n} h", "pin_left": "quedan {n} min",
        "thread_title": "Hilo", "thread_reply_to": "Responder a",
        "follow": "Seguir", "following": "Siguiendo", "hype_level": "Nivel",
        "raid_to": "Raid a", "join": "Unirse", "viewers": "espectadores",
        "customize": "Personalización",
        "cfg_title": "Título del directo", "cfg_title_sub": "Mostrar el título encima del chat",
        "cfg_pinned": "Mensajes fijados", "cfg_pinned_sub": "Mostrar el mensaje fijado",
        "cfg_follow": "Botón seguir", "cfg_follow_sub": "Mostrar el botón Seguir / Dejar de seguir",
        "cfg_streak": "Racha de visionado", "cfg_streak_sub": "Mostrar tu insignia 🔥 de racha",
        "cfg_events": "Encuestas y predicciones", "cfg_events_sub": "Mostrar encuestas, predicciones y hype train",
        "cfg_raids": "Sistema de raid", "cfg_raids_sub": "Banner + unirse automáticamente al canal raideado",
        "cache_section": "Caché de emotes y placas",
        "vod_chat": "Chat del VOD",
        "rewind": "Rebobinar", "back_to_live": "Directo",
        "recover_title": "VOD no listado",
        "unlisted_vod": "VOD no listado",
        "unlisted_gone": "Ya no disponible",
        "unlisted_hint": "Los VODs no listados (eliminados u ocultos) se reconstruyen desde una fuente externa, mientras Twitch siga sirviendo sus segmentos.",
        "home_followed": "Seguidos",
        "see_offline": "Ver los canales desconectados",
        "offline_all_live": "¡Todos tus canales seguidos están en directo!",
        "changelog": "Registro de cambios",
        "changelog_sub": "Todas las novedades, versión por versión",
        "changelog_installed": "Instalada",
        "changelog_available": "Disponible",
        "changelog_failed": "No se pudo cargar el registro de cambios.",
        "changelog_retry": "Reintentar",
        "ob_tour": "Visita guiada",
        "ob_back": "Anterior",
        "ob_tap_here": "Tócalo para continuar",
        "ob_home_title": "Tus directos",
        "ob_home_text": "Tus canales seguidos en directo, el top de directos y tus canales desconectados en su propia pestaña. ¿Sin cuenta? Toca «Seguir» en la página de un canal y aparecerá aquí.",
        "ob_searchtab_title": "Buscar",
        "ob_searchtab_text": "Para encontrar un canal o abrir un VOD.",
        "ob_search_title": "Un canal o un VOD",
        "ob_search_text": "Escribe un nombre para ver sus directos, VODs, destacados, listas y clips: los VODs borrados u ocultos hace poco también aparecen, marcados «VOD no listado». O pega el enlace de un VOD para abrirlo directamente.",
        "ob_library_title": "Mis VODs",
        "ob_library_text": "Tus VODs se reanudan donde los dejaste.",
        "ob_settings_title": "Ajustes",
        "ob_settings_text": "Tu avatar abre los ajustes: cuenta de Twitch (opcional) y sesión web para los puntos del canal, reproductor, chat, copia de seguridad… y el registro de cambios.",
        "ob_player_title": "En el reproductor",
        "ob_tip_zoom": "Separa dos dedos sobre el vídeo para hacer zoom.",
        "ob_tip_seek": "Desliza la barra de un VOD: se muestra el instante elegido.",
        "ob_tip_lock": "Pantalla de bloqueo y Dynamic Island: el directo o el VOD en curso, con sus controles.",
        "ob_tip_more": "Imagen en imagen, temporizador de apagado y el chat con los puntos del canal.",
        "switching_source": "Cambiando de fuente…",
        "fill_screen": "Rellenar la pantalla (horizontal)",
        "fill_screen_sub": "Amplía la imagen hasta los bordes en horizontal, a costa de la parte superior e inferior. Desactivado, se ve la imagen completa con franjas iguales a los lados. Sin efecto en vertical.",
        "web_expired": "Sesión web caducada",
        "web_expired_sub": "Twitch rechazó la sesión web. Los puntos de canal, encuestas y predicciones seguirán no disponibles hasta restablecerla.",
        "web_reconnect": "Restablecer la sesión",
        "history_vods_title": "Tus últimos VODs",
        "history_vods_empty": "Aún no hay ningún VOD en tu historial.",
        "vod_chat_loading": "Cargando el chat…",
        "vod_chat_empty": "Sin mensajes en este punto del VOD",
        "cache_size": "Espacio usado", "cache_files": "archivos",
        "cache_clear": "Vaciar",
        "cache_auto": "Vaciar al salir",
        "cache_auto_sub": "Purga el caché al salir del directo o de la app",
        "account_api": "Conexión API", "account_api_sub": "Chat, canales seguidos y Top",
        "account_web": "Sesión web (puntos)", "account_web_sub": "Necesaria para los puntos del canal",
        "login_points_hint": "Para los puntos del canal, conéctate también con la « Sesión web » en Ajustes ⚙️",
        "points_title": "Puntos del canal",
        "points_connect_title": "Conecta tu cuenta de Twitch",
        "points_connect_desc": "Necesario para ver tu saldo y reclamar cofres.",
        "points_connect_btn": "Iniciar sesión",
        "points_loading": "Cargando recompensas…",
        "points_none": "Sin recompensas disponibles",
        "points_claim_bonus": "Reclamar bono", "points_bonus_claimed": "¡Bono reclamado! 🎉",
        "points_redeem": "Canjear", "points_insufficient": "Insuf.",
        "points_out_of_stock": "Agotado", "points_paused": "En pausa",
        "points_input_ph": "Tu mensaje…", "points_unit": "pts",
        "points_redeemed": "canjeado ✓", "points_error": "Error",
        "points_network_error": "Error de red", "points_missing": "Te faltan",
        "points_by": "por",
        "err_not_enough": "No tienes suficientes puntos", "err_reward_not_found": "Recompensa no encontrada",
        "err_points_disabled": "Puntos desactivados", "err_already_claimed": "Ya reclamado",
        "err_cooldown": "Espera un poco",
        "err_properties_mismatch": "Recompensa modificada, reinténtalo",
        "err_stream_offline": "El stream no está en directo",
        "auto_claim": "Reclamar cofres auto",
        "auto_claim_sub": "Recoge los cofres de puntos en cuanto aparecen.",
        "player_section": "Reproductor de vídeo",
        "sec_general": "General", "sec_player": "Reproductor", "sec_chat": "Chat", "sec_other": "Acerca de",
        "sec_account_sub": "Conexión, sesión web, uso",
        "sec_general_sub": "Idioma, cofres, temporizador, historial, caché",
        "sec_player_sub": "Reproductor inmersivo, baja latencia, depuración",
        "sec_chat_sub": "Mensajes recientes, apariencia, tamaño",
        "sec_other_sub": "Versión y registros", "sec_labs_sub": "Novedades aún en pruebas", "offline_channels": "Desconectados", "cat_followed": "Seguidas", "cat_all": "Todas", "cat_followed_empty": "Ninguna categoría seguida", "cat_followed_empty_msg": "Sigue categorías en Twitch, o abre una categoría y toca «Seguir».", "cat_followed_empty_msg_local": "Abre una categoría y toca «Seguir»: aparecerá aquí.", "ob_skip": "Saltar", "ob_next": "Siguiente", "ob_start": "Empezar", "ob_replay": "Ver el tutorial otra vez", "ob_welcome_title": "Bienvenido a TwitchUnblock", "ob_welcome_text": "Directos y VODs de Twitch en máxima calidad, sin suscripción y con el chat real. Elige tu idioma y haz un recorrido de un minuto por la app.", "bot_commands": "Comandos de bots", "bot_commands_sub": "Nightbot, StreamElements, Fossabot, Moobot: sin escribir en el chat", "bot_commands_filter": "Filtrar comandos", "bot_commands_none": "No se encontraron comandos", "bot_commands_none_msg": "Este canal no usa Nightbot, StreamElements, Fossabot ni Moobot, o no tiene comandos públicos.", "copied_cmd": "{c} copiado", "home_list": "Inicio en lista", "home_list_sub": "Canales en lista como en Twitch (miniatura a la izquierda) en lugar de cuadrícula", "layout_grid": "Ver en cuadrícula", "layout_list": "Ver en lista", "local_follow_empty": "Sigue canales sin cuenta", "local_follow_empty_msg": "Abre la página de un canal y toca «Seguir»: aparecerá aquí en cuanto esté en directo.", "login_optional_msg": "Opcional: para tus canales seguidos de Twitch, el chat y los puntos. Todo lo demás funciona sin cuenta.", "on_this_device": "en este dispositivo",
        "chat_behavior": "Comportamiento del chat",
        "cfg_recent": "Cargar mensajes recientes",
        "cfg_recent_sub": "Twitch no envía nada anterior a tu llegada. Las últimas líneas se piden a recent-messages.robotty.de, un servicio de terceros.",
        "cfg_autocomplete": "Autocompletado",
        "cfg_autocomplete_sub": "Sugiere emotes y nombres mientras escribes.",
        "cfg_deleted": "Mostrar mensajes eliminados",
        "cfg_deleted_sub": "Mantiene tachados los mensajes retirados por moderación en lugar de borrarlos.",
        "copy_message": "Copiar mensaje", "mention_user": "Mencionar",
        "msg_copied": "Mensaje copiado",
        "chat_sizing": "Tamaño del chat",
        "cfg_timestamps": "Marca de tiempo", "cfg_timestamps_sub": "Muestra la hora delante de cada mensaje.",
        "cfg_font_size": "Tamaño del texto", "cfg_msg_spacing": "Espacio entre mensajes",
        "cfg_badge_scale": "Tamaño de las insignias", "cfg_emote_scale": "Tamaño de los emotes",
        "cfg_chat_width": "Ancho del chat",
        "cfg_chat_width_sub": "Solo en horizontal, ya sea en columna o sobre el vídeo.",
        "reset_defaults": "Restablecer valores por defecto",
        "vlc_player": "Reproductor VLC",
        "vlc_player_sub": "Controles propios: doble toque ±10s, rebobinar directo. (sin PiP)",
        "go_live": "EN VIVO",

        // Categorías
        "streams": "Streams", "categories": "Categorías",
        "cat_search_ph": "Buscar una categoría…",
        "load_more": "Cargar más", "more_needs_login": "Sin cuenta, Twitch solo da los 100 primeros. Inicia sesión con Twitch para ver más", "feedback": "Informar de un error o proponer una idea", "feedback_sub": "Un problema o una idea: tu mensaje llega directamente al desarrollador.", "report_problem": "Informar de un problema", "fb_bug": "🐞 Error", "fb_idea": "💡 Idea", "fb_other": "💬 Otro", "fb_ph_bug": "¿Qué pasó? ¿Qué esperabas? ¿En qué canal o VOD?", "fb_ph_idea": "Tu idea, y para qué serviría.", "fb_ph_other": "Tu mensaje.", "fb_contact_ph": "Usuario de Discord o e-mail (opcional)", "fb_info": "Se adjunta automáticamente:", "fb_send": "Enviar", "fb_thanks": "¡Gracias! Tu mensaje se ha enviado.", "fb_failed": "No se pudo enviar, inténtalo más tarde.", "fb_too_many": "Demasiados mensajes seguidos: inténtalo en una hora.", "about_channel": "Acerca de {u}", "followers": "seguidores", "about_empty": "Sin descripción", "show_recent": "Streamers recientes", "show_recent_sub": "Accesos a los últimos canales abiertos, en Buscar.",
        "sort_viewers_desc": "Más espectadores",
        "sort_viewers_asc": "Menos espectadores",
        "sort_name": "Nombre (A → Z)",

        // Temporizador
        "sleep_timer": "Temporizador",
        "sleep_timer_sub": "Detiene la reproducción al terminar el tiempo.",
        "sleep_minutes": "min", "sleep_hour": "1 h", "sleep_2hours": "2 h",
        "sleep_remaining": "Tiempo restante",
        "sleep_cancel": "Cancelar",
        "sleep_add": "+15 min",

        // Depuración
        "vibecoded": "Proyecto vibecodeado: la app se escribe con ayuda de asistentes de IA y luego se revisa y prueba a mano. Pueden colarse errores, avísalos en Discord.", "debug_section": "Funciones en prueba",
        "debug_note": "Novedades aún en pruebas: pueden cambiar o fallar. Tus comentarios son bienvenidos en Discord.",
        "dbg_latency": "Mostrar la latencia",
        "dbg_latency_sub": "Insignia en el reproductor: retraso del directo en segundos",
        "dbg_chat_delay": "Sincronía automática del chat",
        "dbg_chat_delay_sub": "Retrasa los mensajes según tu retraso respecto al directo para cuadrar con la imagen",
        "sleep_custom_ph": "Duración", "sleep_start": "Iniciar",
        "sleep_set": "Ajustar", "sleep_edit": "Modificar",
        "low_latency": "Modo de baja latencia",
        "low_latency_sub": "Se mantiene lo más cerca posible del directo (como en Twitch). Puede cargar más a menudo con conexión lenta. Se aplica al próximo directo.",
        "delete_vod": "Quitar del historial",
        "usage_section": "Uso de la app",
        "usage_returning": "Han vuelto",
        "usage_loyalty_once": "1 solo día", "usage_loyalty_few": "2 a 6 días",
        "usage_loyalty_regular": "7 a 29 días", "usage_loyalty_daily": "30 días o más",
        "usage_avg_days": "med.", "usage_since": "desde el",
        "usage_today": "Hoy", "usage_week": "7 días", "usage_month": "30 días",
        "usage_versions": "Por versión",
        "usage_refresh": "Actualizar",
        "usage_tap_refresh": "Pulsa Actualizar para leer los contadores.",
        "usage_worker_missing": "El servidor aún no tiene las rutas de conteo. Consulta worker/README.md para desplegarlas.",
        "usage_error": "Contadores no disponibles ahora mismo.",
        "usage_share": "Compartir mi uso",
        "usage_share_sub": "Sin sesión: un identificador aleatorio y la versión de la app. Con sesión: tu cuenta de Twitch, para contarte una sola vez en la app y el sitio. Como mucho una vez por hora, sin canales vistos ni dirección IP. Al desactivarlo se borra todo del servidor.",
        "immersive_player": "Reproductor inmersivo",
        "immersive_player_sub": "Controles e info sobre la imagen, que se ocultan solos. Desactivado: reproductor de Apple con sus controles, PiP y pantalla completa del sistema.",
        "quality": "Calidad",
        "rewind_sub": "Retroceder dentro del directo",
        "menu_chat_only": "Solo chat",
        "chat_mode_column": "Chat: columna",
        "chat_mode_overlay": "Chat: superpuesto",
        "chat_mode_hidden": "Chat: oculto",
        "menu_chat_only_sub": "Oculta el vídeo y deja el chat a pantalla completa.",
        "menu_reload_emotes": "Recargar emotes e insignias",
        "menu_reload_emotes_sub": "Vacía la caché y lo descarga todo de nuevo.",
        "menu_reconnect": "Reconectar el chat",
        "menu_reconnect_sub": "Reinicia la conexión sin salir del directo.",
        "menu_color": "Color del nombre",
        "menu_color_sub": "Cambia tu color en el chat.",
        "menu_needs_login": "Requiere iniciar sesión",
        "menu_chatters": "Espectadores del chat",
        "menu_chatters_sub": "Quién está en el chat ahora.",
        "menu_chatters_search": "Filtrar nombres…",
        "menu_chatters_empty": "Nadie anunciado en este canal",
        "menu_chatters_waiting": "Esperando la lista del chat…",
        "menu_chatters_note": "Twitch cerró su API de presencia: solo el IRC sigue anunciando las llegadas, y únicamente en canales de tamaño modesto. La lista puede quedarse vacía en directos grandes.",
        "color_needs_relogin": "Cierra sesión y vuelve a entrar: el permiso «cambiar el color» se añadió después de tu conexión.",
        "color_network": "No se pudo contactar con Twitch.",
        "color_bad_request": "Color rechazado por Twitch.",
        "color_failed": "Twitch rechazó el cambio de color.",
        "role_broadcaster": "Streamer", "role_moderator": "Moderadores",
        "ph_search": "Streamer, enlace o ID de VOD…",
        "btn_open": "Abrir",
        "hint_is_vod": "Abrirá este VOD",
        "hint_is_channel": "Buscará este canal",
        "err_bad_vod": "Enlace o ID de VOD no válido.",
        "search_empty_title": "Busca un canal o pega un enlace",
        "search_empty_msg": "Escribe el nombre de un streamer o pega el enlace / ID de un VOD: la app reconoce ambos.",
        "no_followed_live": "Ninguno de tus canales está en directo",
        "no_followed_live_msg": "Echa un vistazo al Top o a las categorías mientras tanto.",
        "history_vods_empty_msg": "Los VODs que reproduzcas aparecerán aquí, con reanudación.",
        "chat_sync_hint": "¿El chat va adelantado o atrasado respecto a la imagen?",
        "chat_sync_later": "Retrasar el chat (+1 s)",
        "chat_sync_earlier": "Adelantar el chat (−1 s)",
        "chat_sync_reset": "Volver solo a la sincronía automática",
        "chat_sync_adjust": "Ajuste de la sincronía",
        "chat_sync_adjust_sub": "¿El chat sigue adelantado? Añade unos segundos. ¿Atrasado? Quita algunos. También desde la etiqueta ⏱ encima del chat.",
        "lang_ai_note": "Traducido con IA, aún sin revisar: si algo suena raro, avísanos.",
        "lang_ai_report": "Reportar un error de traducción",
        "lang_ai_badge": "Traducido con IA",
        "switch_account": "Cambiar de cuenta",
        "switch_account_sub": "Twitch te pedirá tus credenciales: inicia sesión con la otra cuenta.",
        "vod_muted_here": "Sonido silenciado por Twitch (música protegida)",
        "vod_muted_skip": "Saltar",
        "vod_unmuted": "Sonido original restaurado en las partes silenciadas",
        "restore_muted": "Restaurar el sonido silenciado",
        "restore_muted_sub": "Twitch silencia las partes con música protegida. Uno o dos días después del directo, el original aún está disponible: la app lo restaura cuando puede. Sin efecto por AirPlay.",
        "appearance": "Apariencia",
        "accent_color": "Color de acento",
        "background_theme": "Fondo",
        "accent_twitch": "Morado Twitch",
        "accent_blue": "Azul",
        "accent_green": "Verde",
        "accent_pink": "Rosa",
        "accent_orange": "Naranja",
        "accent_red": "Rojo",
        "accent_teal": "Turquesa",
        "bg_dark": "Oscuro",
        "bg_oled": "Negro OLED",
        "bg_slate": "Pizarra",
        "liquid_glass": "Liquid Glass",
        "liquid_glass_sub": "Barra de pestañas flotante y botones de cristal, al estilo de iOS 26.",
        "liquid_glass_unavailable": "Requiere iOS 26 o posterior.",
        "fb_add_photos": "Añadir capturas",
        "fb_mine": "Mis reportes",
        "fb_mine_empty": "Los reportes enviados desde la app aparecerán aquí, con las respuestas.",
        "fb_thanks_follow": "¡Gracias! Sigue la respuesta en «Mis reportes».",
        "fb_reply_ph": "Responder…",
        "fb_reply_send": "Enviar",
        "fb_reply_failed": "Respuesta no enviada, inténtalo de nuevo.",
        "fb_team": "TwitchUnblock",
        "fb_you": "Tú",
        "fb_status_line": "Estado: {s}",
        "fb_gone": "Este reporte ya no está disponible.",
        "fb_status_new": "Recibido",
        "fb_status_accepted": "Aceptado",
        "fb_status_progress": "En curso",
        "fb_status_done": "Hecho",
        "fb_status_refused": "Rechazado",
        "adm_feedback": "Gestionar comentarios",
        "adm_feedback_sub": "Responder, cambiar el estado, borrar — solo visible para tu cuenta",
        "adm_all": "Todos",
        "adm_await": "Por responder",
        "adm_awaiting": "Respuesta de la persona",
        "adm_empty": "Ningún comentario en este estado.",
        "adm_them": "La persona",
        "adm_reply_ph": "Responder (la persona lo verá)…",
        "adm_delete": "Borrar",
        "adm_delete_confirm": "¿Borrar este comentario y sus fotos?",
        "adm_contact": "Contacto",
        "adm_info": "Información técnica",
        "adm_failed": "No se pudo hacer, inténtalo de nuevo.",
        "adm_hook_ok": "Discord: último envío correcto ({d})",
        "adm_hook_fail": "Discord: último envío rechazado ({d}) — {e}",
        "adm_hook_missing": "Discord: falta el secreto FEEDBACK_WEBHOOK en el Worker",
        "adm_hook_never": "Discord: nada enviado desde la actualización",
        "adm_hook_test": "Probar el envío a Discord",
        "adm_hook_test_ok": "Mensaje de prueba enviado a Discord.",
    ],
    // Russe : dans son propre fichier (Localization/RussianStrings.swift).
    .ru: kRussianStrings,
]

/// Une clé absente d'une langue retombe sur l'anglais, puis sur la clé
/// elle-même : une traduction en retard n'affiche jamais un identifiant.
func translate(_ key: String, _ lang: Lang) -> String {
    translations[lang]?[key] ?? translations[.en]?[key] ?? key
}
