import Foundation

// Traductions russes (faites avec l'IA, relues par personne : les retours
// d'utilisateurs russophones sont les bienvenus). Une clé absente retombe
// sur l'anglais.
let kRussianStrings: [String: String] = [
    "title": "Twitch без подписки",
    "tab_home": "Главная",
    "tab_search": "Поиск",
    "tab_library": "Мои VOD",
    "tab_direct": "Ссылка / ID",
    "settings": "Настройки",
    "tab_history": "VOD",
    "ph_streamer": "Стример (напр.: buster)",
    "ph_keyword": "Ключевое слово (напр.: хоррор)",
    "ph_id": "ID или ссылка на VOD",
    "btn_unlock": "Разблокировать",
    "btn_search": "Найти",
    "btn_watch_live": "Смотреть эфир",
    "btn_copy": "Копировать",
    "btn_pip": "PiP",
    "btn_refresh": "🔄 Обновить",
    "btn_logout": "Выйти",
    "btn_login_twitch": "🟣 Войти через Twitch",
    "btn_clear": "Очистить",
    "loading": "Загрузка...",
    "loading_vod": "Загрузка VOD...",
    "loading_channels": "Загрузка ваших каналов...",
    "loading_top": "Загрузка топа...",
    "vod_ready": "VOD воспроизводится!",
    "live_on": "В ЭФИРЕ",
    "offline": "НЕ В СЕТИ",
    "offline_since": "Не в сети: ",
    "no_vod": "VOD не найдены.",
    "no_live": "Сейчас нет каналов в эфире.",
    "vods_found": "VOD найдено.",
    "not_found": "❌ Стример не найден.",
    "err_missing": "Не указано имя.",
    "err_network": "Ошибка сети.",
    "err_live": "Ошибка трансляции.",
    "err_conn": "Ошибка подключения.",
    "err_loading": "Ошибка загрузки данных.",
    "login_prompt": "Войдите, чтобы видеть любимые каналы.",
    "login_required": "Войдите, чтобы видеть текущие трансляции.",
    "session_expired": "Сессия истекла. Войдите снова.",
    "lbl_vod_history": "Недавно просмотренные VOD",
    "lbl_channel_history": "Недавние стримеры",
    "followed_channels": "Отслеживаемые каналы",
    "top_streams": "Топ трансляций",
    "top_fr": "Франция",
    "top_world": "Весь мир",
    "top_lang": "Топ трансляций",
    "top_lang_sub": "Язык стримеров. По умолчанию — язык устройства ({l}).",
    "lang_auto": "Устройство",
    "copied": "Ссылка скопирована!",
    "day": "дн.",
    "hour": "ч",
    "min": "мин",
    "offline_msg": "Сейчас нет трансляции.",
    "open_vlc": "Открыть в VLC",
    "open_outplayer": "Открыть в Outplayer",
    "open_infuse": "Открыть в Infuse",
    "proxy": "Прокси",
    "reduce": "Свернуть",
    "back": "Назад",
    "live_badge": "В ЭФИРЕ",
    "no_result": "Ничего не найдено",
    "confirm_logout": "Вы уверены, что хотите выйти?",
    "cancel": "Отменить",
    "clear_logs": "Очистить логи",
    "confirm": "Подтвердить?",
    "erase": "Очистить",
    "export": "📤 Экспорт",
    "logs_empty": "Логов нет",
    "logs_hint": "Запустите VOD или трансляцию, чтобы увидеть логи",
    "about": "О приложении",
    "version": "Версия 1.0.0",
    "about_desc": "Смотрите VOD и трансляции Twitch без подписки, в максимальном качестве. Ничего не нужно настраивать.",
    "show_logs": "Показать системные логи",
    "connected": "Подключено",
    "not_connected": "Не подключено",
    "history": "История",
    "vods": "VOD",
    "channels": "Каналы",
    "proxy_sub": "Отключите, чтобы сэкономить ресурсы сервера (полезно для VLC)",
    "proxy_enable": "Включить прокси",
    "twitch_account": "Аккаунт Twitch",
    "language": "Язык",
    "settings_source": "Видеосервер / источник",
    "source_auto": "Авто",
    "source_auto_sub": "Лучший доступный источник",
    "source_luminous": "Luminous",
    "source_luminous_sub": "Без рекламы (рекомендуется)",
    "source_twitch": "Официальный Twitch",
    "source_twitch_sub": "С рекламой",
    "source_cloudflare": "Cloudflare Worker",
    "source_cloudflare_sub": "Личный прокси",
    "chat_connected": "Чат подключён",
    "chat_connecting": "Подключение...",
    "chat_send_ph": "Отправить сообщение…",
    "chat_connecting_ph": "Подключение…",
    "chat_follow": "Отслеживать",
    "chat_first_message": "Первое сообщение",
    "poll_results": "Результаты",
    "poll_multi": "Можно выбрать несколько вариантов",
    "poll_votes": "голосов",
    "pred_result": "Результат",
    "pred_tap_to_bet": "Нажмите на исход, чтобы сделать прогноз",
    "pred_bet_on": "Прогноз на «{o}»",
    "pred_bet": "Поставить",
    "pred_balance": "Баланс",
    "pred_all": "Макс.",
    "pred_my_bet": "Ваш прогноз: {n} баллов на «{o}»",
    "pred_need_login": "Чтобы делать прогнозы, подключите сессию Twitch кнопкой баллов канала",
    "pred_bet_failed": "Прогноз не отправлен, попробуйте снова",
    "pred_closed": "Приём прогнозов закрыт",
    "pred_one_outcome": "Вы уже сделали прогноз на другой исход",
    "pred_max": "Максимум: 250 000 баллов за прогноз",
    "pred_min": "Минимум: 10 баллов",
    "hide_bots": "Скрывать ботов",
    "hide_bots_sub": "Nightbot, StreamElements, Fossabot…",
    "hide_commands": "Скрывать команды",
    "hide_commands_sub": "Сообщения, начинающиеся с «!».",
    "muted_words": "Скрытые слова",
    "muted_words_sub": "Через запятую: сообщения с ними не показываются.",
    "hidden_users": "Скрыто пользователей: {n}",
    "clear": "Очистить",
    "hide_user": "Скрыть в чате",
    "unhide_user": "Снова показывать в чате",
    "clips": "Клипы",
    "no_clips": "Нет клипов за этот период",
    "highlights": "Хайлайты",
    "no_highlights": "Нет хайлайтов",
    "backup": "Резервная копия",
    "backup_sub": "Экспортируйте отслеживаемые каналы, категории и настройки в файл, чтобы импортировать их в другом месте (в приложении или на сайте).",
    "export_data": "Экспорт",
    "import_data": "Импорт",
    "export_done": "Файл экспортирован",
    "import_done": "Импорт завершён, добавлено каналов: %d",
    "import_bad": "Этот файл не является резервной копией TwitchUnblock",
    "playlists": "Плейлисты",
    "play_all": "Воспроизвести все",
    "videos_count": "Видео: %d",
    "no_playlists": "Нет плейлистов",
    "err_clip": "Клип не найден",
    "period_day": "24 ч",
    "period_week": "7 дн.",
    "period_month": "30 дн.",
    "period_all": "Всё время",
    "notif_live": "Уведомления о трансляциях",
    "notif_live_sub": "Сообщает, когда отслеживаемый канал выходит в эфир (проверка в фоне, когда iOS это позволяет; отслеживаемые в Twitch и на этом устройстве).",
    "notif_test": "Отправить тестовое уведомление",
    "notif_test_title": "TwitchUnblock",
    "notif_test_body": "Уведомления работают 🎉",
    "notif_test_sent": "Отправлено: оно придёт через 3 с (выйдите из приложения, чтобы увидеть его как настоящее).",
    "notif_test_denied": "Уведомления запрещены. Разрешите их: Настройки iOS → TwitchUnblock.",
    "notif_last_never": "Фоновых проверок пока не было. Момент выбирает iOS: оставьте приложение в фоне (не закрывая его) на несколько часов.",
    "notif_last_run": "Последняя фоновая проверка: {t}",
    "notif_last_failed": "ошибка (сеть или токен)",
    "notif_bg_off": "«Обновление контента» выключено (или включён режим энергосбережения): iOS не будет будить приложение. Настройки iOS → Основные → Обновление контента.",
    "notif_bg_refused": "iOS отказалась запланировать проверку",
    "web_banner_title": "Подключите веб-сессию",
    "web_banner_msg": "Для баллов канала, автосбора сундуков и прогнозов: один раз войдите на twitch.tv в приложении.",
    "web_banner_btn": "Подключить",
    "announcement_open": "Открыть",
    "dont_show_again": "Больше не показывать",
    "notif_live_title": "{u} в эфире",
    "chapters": "Главы",
    "close": "Закрыть",
    "made_by": "Автор:",
    "source_ios": "Исходный код приложения",
    "web_version": "Веб-версия",
    "credits_thanks": "Спасибо BetterTTV, FrankerFaceZ, 7TV, recent-messages и Luminous.",
    "not_affiliated": "Независимый проект, не связан с Twitch.",
    "update_title": "Доступно обновление",
    "update_msg": "Вышла версия {v} (у вас {c}). Обновите приложение через Feather, SideStore или AltStore.",
    "update_whats_new": "Вот что изменилось с вашей версии:",
    "update_open": "Обновить",
    "later": "Позже",
    "update_available": "Доступно обновление: {v}",
    "update_check": "Проверить обновления",
    "update_none": "У вас последняя версия",
    "version_label": "Версия",
    "discord_join": "Присоединиться к Discord",
    "discord_title": "Присоединяйтесь к Discord",
    "discord_msg": "Новости, баги, идеи: сообщество TwitchUnblock — в Discord. Его также можно найти позже в разделе Настройки → О приложении.",
    "update_msg_short": "Доступна новая версия TwitchUnblock. Установите её через Feather, SideStore или AltStore.",
    "see_channel": "Открыть канал",
    "highlight_words": "Выделяемые слова",
    "highlight_words_sub": "Через запятую. Сообщения с ними (или с упоминанием вас) выделяются.",
    "pinned": "Закреплённое сообщение",
    "pinned_by": "Закрепил(а) {u}",
    "pinned_short": "Закреплено",
    "just_now": "только что",
    "minutes_ago": "{n} мин назад",
    "hours_ago": "{n} ч назад",
    "pin_left": "осталось {n} мин",
    "thread_title": "Ветка",
    "thread_reply_to": "Ответить",
    "follow": "Отслеживать",
    "following": "Отслеживается",
    "hype_level": "Уровень",
    "raid_to": "Рейд на",
    "join": "Перейти",
    "viewers": "зрителей",
    "customize": "Персонализация",
    "cfg_title": "Название трансляции",
    "cfg_title_sub": "Показывать название над чатом",
    "cfg_pinned": "Закреплённые сообщения",
    "cfg_pinned_sub": "Показывать баннер закреплённого сообщения",
    "cfg_follow": "Кнопка «Отслеживать»",
    "cfg_follow_sub": "Показывать кнопку «Отслеживать» / «Не отслеживать»",
    "cfg_streak": "Серия просмотров",
    "cfg_streak_sub": "Показывать значок 🔥 вашей серии",
    "cfg_events": "Опросы и прогнозы",
    "cfg_events_sub": "Показывать опросы, прогнозы и хайп-трейн",
    "cfg_raids": "Рейды",
    "cfg_raids_sub": "Баннер + автопереход на канал рейда",
    "cache_section": "Кэш смайликов и значков",
    "vod_chat": "Чат VOD",
    "rewind": "Перемотка",
    "back_to_live": "К эфиру",
    "recover_title": "VOD вне списка",
    "unlisted_vod": "VOD вне списка",
    "unlisted_gone": "Больше недоступно",
    "unlisted_hint": "VOD вне списка (удалённые или скрытые) восстанавливаются по данным внешнего источника, пока Twitch ещё отдаёт их сегменты.",
    "home_followed": "Отслеживаемые",
    "see_offline": "Показать каналы не в сети",
    "offline_all_live": "Все отслеживаемые каналы в эфире!",
    "changelog": "Список изменений",
    "changelog_sub": "Все новшества, версия за версией",
    "changelog_installed": "Установлена",
    "changelog_available": "Доступна",
    "changelog_failed": "Не удалось загрузить список изменений.",
    "changelog_retry": "Повторить",
    "ob_tour": "Пройти обзор",
    "ob_back": "Назад",
    "ob_tap_here": "Нажмите, чтобы продолжить",
    "ob_home_title": "Ваши трансляции",
    "ob_home_text": "Отслеживаемые каналы в эфире, топ трансляций, а каналы не в сети — на отдельной вкладке. Нет аккаунта? Нажмите «Отслеживать» на странице канала, и он появится здесь.",
    "ob_searchtab_title": "Поиск",
    "ob_searchtab_text": "Чтобы найти канал или открыть VOD.",
    "ob_search_title": "Канал или VOD",
    "ob_search_text": "Введите ник, чтобы увидеть трансляции, VOD, хайлайты, плейлисты и клипы канала — недавно удалённые или скрытые VOD тоже там, с пометкой «VOD вне списка». Или вставьте ссылку на VOD, чтобы сразу перейти к просмотру.",
    "ob_library_title": "Мои VOD",
    "ob_library_text": "Ваши VOD продолжаются с того места, где вы остановились.",
    "ob_settings_title": "Настройки",
    "ob_settings_text": "Ваш аватар открывает настройки: аккаунт Twitch (необязательно) и веб-сессия для баллов канала, плеер, чат, резервная копия… и список изменений.",
    "ob_player_title": "В плеере",
    "ob_tip_zoom": "Разведите два пальца на видео, чтобы увеличить.",
    "ob_tip_seek": "Потяните шкалу воспроизведения VOD — появится момент, к которому вы перематываете.",
    "ob_tip_lock": "Экран блокировки и Dynamic Island: текущая трансляция или VOD с элементами управления.",
    "ob_tip_more": "Картинка в картинке, таймер сна и чат с баллами канала.",
    "switching_source": "Смена источника…",
    "fill_screen": "Заполнять экран (горизонтально)",
    "fill_screen_sub": "В горизонтальной ориентации растягивает изображение до краёв, обрезая верх и низ. Если выключено, изображение видно целиком, с одинаковыми полосами по бокам. В вертикальной ориентации не действует.",
    "web_expired": "Веб-сессия истекла",
    "web_expired_sub": "Twitch отклонил веб-сессию. Баллы канала, опросы и прогнозы недоступны, пока она не будет восстановлена.",
    "web_reconnect": "Восстановить сессию",
    "history_vods_title": "Ваши недавние VOD",
    "history_vods_empty": "В истории пока нет VOD.",
    "vod_chat_loading": "Загрузка чата…",
    "vod_chat_empty": "В этот момент VOD сообщений нет",
    "cache_size": "Занятое место",
    "cache_files": "файлов",
    "cache_clear": "Очистить",
    "cache_auto": "Очищать при выходе",
    "cache_auto_sub": "Очищает кэш при выходе из трансляции или приложения",
    "account_api": "Вход через API",
    "account_api_sub": "Чат, отслеживаемые каналы и топ",
    "account_web": "Веб-сессия (баллы)",
    "account_web_sub": "Нужна для баллов канала",
    "login_points_hint": "Для баллов канала также подключите «Веб-сессию» в настройках ⚙️",
    "points_title": "Баллы канала",
    "points_connect_title": "Подключите аккаунт Twitch",
    "points_connect_desc": "Нужно, чтобы видеть баланс и забирать сундуки.",
    "points_connect_btn": "Войти",
    "points_loading": "Загрузка наград…",
    "points_none": "Нет доступных наград",
    "points_claim_bonus": "Забрать бонус",
    "points_bonus_claimed": "Бонус получен! 🎉",
    "points_redeem": "Получить",
    "points_insufficient": "Мало",
    "points_out_of_stock": "Нет в наличии",
    "points_paused": "Приостановлено",
    "points_input_ph": "Ваше сообщение…",
    "points_unit": "баллов",
    "points_redeemed": "получено ✓",
    "points_error": "Ошибка",
    "points_network_error": "Ошибка сети",
    "points_missing": "Не хватает",
    "points_by": "от",
    "err_not_enough": "Недостаточно баллов",
    "err_reward_not_found": "Награда не найдена",
    "err_points_disabled": "Баллы отключены",
    "err_already_claimed": "Уже получено",
    "err_cooldown": "Подождите немного",
    "err_properties_mismatch": "Награда изменилась, попробуйте снова",
    "err_stream_offline": "Канал не в эфире",
    "auto_claim": "Автосбор сундуков",
    "auto_claim_sub": "Забирает сундуки с баллами, как только они появляются.",
    "player_section": "Видеоплеер",
    "sec_general": "Основные",
    "sec_player": "Плеер",
    "sec_chat": "Чат",
    "sec_other": "О приложении",
    "sec_account_sub": "Вход, веб-сессия, использование",
    "sec_general_sub": "Язык, сундуки, таймер сна, история, кэш",
    "sec_player_sub": "Иммерсивный плеер, низкая задержка, отладка",
    "sec_chat_sub": "Недавние сообщения, внешний вид, размеры",
    "sec_other_sub": "Версия и логи",
    "sec_labs_sub": "Новые функции в доработке",
    "offline_channels": "Не в сети",
    "cat_followed": "Отслеживаемые",
    "cat_all": "Все",
    "cat_followed_empty": "Нет отслеживаемых категорий",
    "cat_followed_empty_msg": "Отслеживайте категории в Twitch или откройте категорию и нажмите «Отслеживать».",
    "cat_followed_empty_msg_local": "Откройте категорию и нажмите «Отслеживать» — она появится здесь.",
    "ob_skip": "Пропустить",
    "ob_next": "Далее",
    "ob_start": "Поехали",
    "ob_replay": "Пройти обзор заново",
    "ob_welcome_title": "Добро пожаловать в TwitchUnblock",
    "ob_welcome_text": "Трансляции и VOD с Twitch в максимальном качестве, без подписки и с настоящим чатом. Выберите язык, а затем за минуту познакомьтесь с приложением.",
    "bot_commands": "Команды ботов",
    "bot_commands_sub": "Nightbot, StreamElements, Fossabot, Moobot — без ввода в чат",
    "bot_commands_filter": "Фильтр команд",
    "bot_commands_none": "Команды не найдены",
    "bot_commands_none_msg": "Этот канал не использует Nightbot, StreamElements, Fossabot или Moobot либо у него там нет публичных команд.",
    "copied_cmd": "Скопировано: {c}",
    "home_list": "Главная списком",
    "home_list_sub": "Каналы списком, как в Twitch (превью слева), а не сеткой",
    "layout_grid": "Показать сеткой",
    "layout_list": "Показать списком",
    "local_follow_empty": "Отслеживайте каналы без аккаунта",
    "local_follow_empty_msg": "Откройте страницу канала и нажмите «Отслеживать» — он появится здесь, как только выйдет в эфир.",
    "login_optional_msg": "Необязательно: для отслеживаемых каналов Twitch, чата и баллов канала. Всё остальное работает без аккаунта.",
    "on_this_device": "на этом устройстве",
    "chat_behavior": "Поведение чата",
    "cfg_recent": "Загружать недавние сообщения",
    "cfg_recent_sub": "Twitch не присылает сообщения, отправленные до вашего входа. Последние строки загружаются с recent-messages.robotty.de — стороннего сервиса.",
    "cfg_autocomplete": "Автодополнение",
    "cfg_autocomplete_sub": "Предлагает смайлики и ники при вводе.",
    "cfg_deleted": "Показывать удалённые сообщения",
    "cfg_deleted_sub": "Сообщения, удалённые модерацией, остаются зачёркнутыми, а не исчезают.",
    "copy_message": "Копировать сообщение",
    "mention_user": "Упомянуть",
    "msg_copied": "Сообщение скопировано",
    "chat_sizing": "Размеры чата",
    "cfg_timestamps": "Метки времени",
    "cfg_timestamps_sub": "Показывает время перед каждым сообщением.",
    "cfg_font_size": "Размер шрифта",
    "cfg_msg_spacing": "Интервал между сообщениями",
    "cfg_badge_scale": "Размер значков",
    "cfg_emote_scale": "Размер смайликов",
    "cfg_chat_width": "Ширина чата",
    "cfg_chat_width_sub": "Только в горизонтальной ориентации — и для чата колонкой, и для чата поверх видео.",
    "reset_defaults": "Вернуть стандартные значения",
    "vlc_player": "Плеер VLC",
    "vlc_player_sub": "Свои элементы управления: двойное касание ±10 с, перемотка эфира. (без PiP)",
    "go_live": "В ЭФИРЕ",
    "streams": "Трансляции",
    "categories": "Категории",
    "cat_search_ph": "Найти категорию…",
    "load_more": "Загрузить ещё",
    "more_needs_login": "Без аккаунта Twitch отдаёт только первые 100. Войдите через Twitch, чтобы увидеть больше",
    "feedback": "Сообщить об ошибке или предложить идею",
    "feedback_sub": "Проблема или идея: ваше сообщение попадёт прямо к разработчику.",
    "report_problem": "Сообщить о проблеме",
    "fb_bug": "🐞 Ошибка",
    "fb_idea": "💡 Идея",
    "fb_other": "💬 Другое",
    "fb_ph_bug": "Что произошло? Чего вы ожидали? На каком канале или VOD?",
    "fb_ph_idea": "Ваша идея и чем она была бы полезна.",
    "fb_ph_other": "Ваше сообщение.",
    "fb_contact_ph": "Ник в Discord или e-mail (необязательно)",
    "fb_info": "Прикрепляется автоматически:",
    "fb_send": "Отправить",
    "fb_thanks": "Спасибо! Ваше сообщение отправлено.",
    "fb_failed": "Не удалось отправить, попробуйте позже.",
    "fb_too_many": "Слишком много сообщений подряд: попробуйте через час.",
    "about_channel": "О канале {u}",
    "followers": "фолловеров",
    "about_empty": "Описания пока нет",
    "show_recent": "Недавние стримеры",
    "show_recent_sub": "Быстрый доступ к недавно открытым каналам в поиске.",
    "sort_viewers_desc": "Больше зрителей",
    "sort_viewers_asc": "Меньше зрителей",
    "sort_name": "Название (А → Я)",
    "sleep_timer": "Таймер сна",
    "sleep_timer_sub": "Останавливает воспроизведение по истечении времени.",
    "sleep_minutes": "мин",
    "sleep_hour": "1 ч",
    "sleep_2hours": "2 ч",
    "sleep_remaining": "Осталось",
    "sleep_cancel": "Отменить",
    "sleep_add": "+15 мин",
    "vibecoded": "Проект в стиле вайб-кодинга: приложение пишется с помощью ИИ-ассистентов, затем проверяется и тестируется вручную. Ошибки могут проскочить — сообщайте о них в Discord.",
    "debug_section": "Тестовые функции",
    "debug_note": "Новые функции ещё дорабатываются: они могут измениться или работать некорректно. Ждём ваших отзывов в Discord.",
    "dbg_latency": "Показывать задержку",
    "dbg_latency_sub": "Значок в плеере: отставание от эфира в секундах",
    "dbg_chat_delay": "Автосинхронизация чата",
    "dbg_chat_delay_sub": "Задерживает сообщения на ваше отставание от эфира, чтобы они совпадали с видео",
    "sleep_custom_ph": "Длительность",
    "sleep_start": "Запустить",
    "sleep_set": "Задать",
    "sleep_edit": "Изменить",
    "low_latency": "Режим низкой задержки",
    "low_latency_sub": "Держится как можно ближе к эфиру (как в Twitch). На медленном соединении может чаще подгружаться. Применяется к следующей открытой трансляции.",
    "delete_vod": "Удалить из истории",
    "usage_section": "Использование приложения",
    "usage_returning": "Вернулись",
    "usage_loyalty_once": "Только 1 день",
    "usage_loyalty_few": "От 2 до 6 дней",
    "usage_loyalty_regular": "От 7 до 29 дней",
    "usage_loyalty_daily": "30 дней и больше",
    "usage_avg_days": "в ср.",
    "usage_since": "с",
    "usage_today": "Сегодня",
    "usage_week": "7 дней",
    "usage_month": "30 дней",
    "usage_versions": "По версиям",
    "usage_refresh": "Обновить",
    "usage_tap_refresh": "Нажмите «Обновить», чтобы получить данные счётчиков.",
    "usage_worker_missing": "На сервере ещё нет маршрутов подсчёта. Как их развернуть — см. worker/README.md.",
    "usage_error": "Счётчики сейчас недоступны.",
    "usage_share": "Делиться статистикой",
    "usage_share_sub": "Без входа: случайный идентификатор установки и версия приложения. После входа: ваш аккаунт Twitch, чтобы вас учитывали один раз в приложении и на сайте. Не чаще раза в час, без просмотренных каналов и IP-адреса. При отключении всё удаляется с сервера.",
    "immersive_player": "Иммерсивный плеер",
    "immersive_player_sub": "Элементы управления и информация поверх изображения, скрываются сами. Если выключено — плеер Apple со своими элементами управления, PiP и системным полноэкранным режимом.",
    "quality": "Качество",
    "rewind_sub": "Перемотать назад в прямом эфире",
    "menu_chat_only": "Только чат",
    "chat_mode_column": "Чат: колонка",
    "chat_mode_overlay": "Чат: поверх видео",
    "chat_mode_hidden": "Чат: скрыт",
    "menu_chat_only_sub": "Скрывает видео и отдаёт чату весь экран.",
    "menu_reload_emotes": "Обновить смайлики и значки",
    "menu_reload_emotes_sub": "Очищает кэш и загружает всё заново.",
    "menu_reconnect": "Переподключить чат",
    "menu_reconnect_sub": "Перезапускает соединение, не покидая трансляцию.",
    "menu_color": "Цвет ника",
    "menu_color_sub": "Измените свой цвет в чате.",
    "menu_needs_login": "Требуется вход",
    "menu_chatters": "Участники чата",
    "menu_chatters_sub": "Кто сейчас в чате.",
    "menu_chatters_search": "Фильтр по никам…",
    "menu_chatters_empty": "На этом канале никого не видно",
    "menu_chatters_waiting": "Ожидание списка чата…",
    "menu_chatters_note": "Twitch закрыл API присутствия: о входящих сообщает только IRC, и лишь на небольших каналах. Поэтому на крупных трансляциях список может оставаться пустым.",
    "color_needs_relogin": "Выйдите и войдите снова: разрешение «изменение цвета» добавлено после вашего входа.",
    "color_network": "Не удалось связаться с Twitch.",
    "color_bad_request": "Twitch отклонил цвет.",
    "color_failed": "Twitch отклонил смену цвета.",
    "role_broadcaster": "Стример",
    "role_moderator": "Модераторы",
    "ph_search": "Стример, ссылка или ID VOD…",
    "btn_open": "Открыть",
    "hint_is_vod": "Откроется VOD",
    "hint_is_channel": "Начнётся поиск канала",
    "err_bad_vod": "Неверная ссылка или ID VOD.",
    "search_empty_title": "Найдите канал или вставьте ссылку",
    "search_empty_msg": "Введите ник стримера или вставьте ссылку / ID VOD — приложение распознаёт и то и другое.",
    "no_followed_live": "Ни один из ваших каналов не в эфире",
    "no_followed_live_msg": "А пока загляните в топ или в категории.",
    "history_vods_empty_msg": "Здесь появятся VOD, которые вы запускаете, с продолжением просмотра.",
    "chat_sync_hint": "Чат опережает видео или отстаёт?",
    "chat_sync_later": "Задержать чат (+1 с)",
    "chat_sync_earlier": "Ускорить чат (−1 с)",
    "chat_sync_reset": "Только автосинхронизация",
    "chat_sync_adjust": "Подстройка синхронизации",
    "chat_sync_adjust_sub": "Чат всё ещё опережает видео? Добавьте пару секунд. Отстаёт? Уберите. То же можно сделать значком ⏱ над чатом.",
    "lang_ai_note": "Перевод сделан с помощью ИИ и ещё не проверен: если что-то звучит странно, сообщите нам.",
    "lang_ai_report": "Сообщить об ошибке перевода",
    "lang_ai_badge": "Переведено с помощью ИИ",
    "switch_account": "Сменить аккаунт",
    "switch_account_sub": "Twitch запросит данные для входа: войдите в другой аккаунт.",
    "vod_muted_here": "Звук отключён Twitch (защищённая музыка)",
    "vod_muted_skip": "Пропустить",
    "vod_unmuted": "Исходный звук восстановлен на заглушённых фрагментах",
    "restore_muted": "Восстанавливать заглушённый звук",
    "restore_muted_sub": "Twitch отключает звук во фрагментах с защищённой музыкой. В течение дня-двух после трансляции оригинал ещё доступен — приложение возвращает его, когда может. Не работает через AirPlay.",
    "appearance": "Оформление",
    "accent_color": "Цвет акцента",
    "background_theme": "Фон",
    "accent_twitch": "Фиолетовый Twitch",
    "accent_blue": "Синий",
    "accent_green": "Зелёный",
    "accent_pink": "Розовый",
    "accent_orange": "Оранжевый",
    "accent_red": "Красный",
    "accent_teal": "Бирюзовый",
    "bg_dark": "Тёмный",
    "bg_oled": "Чёрный OLED",
    "bg_slate": "Сланцевый",
    "liquid_glass": "Liquid Glass",
    "liquid_glass_sub": "Плавающая панель вкладок и стеклянные кнопки в стиле iOS 26.",
    "liquid_glass_unavailable": "Нужна iOS 26 или новее.",
    "fb_add_photos": "Добавить скриншоты",
    "fb_mine": "Мои обращения",
    "fb_mine_empty": "Здесь появятся обращения, отправленные из приложения, вместе с ответами.",
    "fb_thanks_follow": "Спасибо! Ответ появится в разделе «Мои обращения».",
    "fb_reply_ph": "Ответить…",
    "fb_reply_send": "Отправить",
    "fb_reply_failed": "Ответ не отправлен, попробуйте ещё раз.",
    "fb_team": "TwitchUnblock",
    "fb_you": "Вы",
    "fb_status_line": "Статус: {s}",
    "fb_gone": "Это обращение больше недоступно.",
    "fb_status_new": "Получено",
    "fb_status_accepted": "Принято",
    "fb_status_progress": "В работе",
    "fb_status_done": "Готово",
    "fb_status_refused": "Отклонено",
]
